import {healthyBodyFatRange,type PhysicalAssessment} from "./athlete-progress.ts";

export type AnalyticsAthlete={id:string;nombre:string;historialFisico?:unknown[]};
export type AthleteAnalytics={id:string;nombre:string;latest?:PhysicalAssessment;healthScore?:number;performanceScore?:number;balanceScore?:number;improvementScore?:number;performanceRank?:number;peerLabel:string;peerSize:number;dataQuality:number;trend:"up"|"stable"|"down"|"baseline";strengths:string[];priorities:string[]};

const higher=["lagartijas","sentadillas","abdominales","burpees","planchaSegundos","saltoHorizontalCm","saltoVerticalCm","sitAndReachCm","equilibrioSegundos","fuerzaAgarreKg","navetteNivel"] as const;
const lower=["sprint10mSegundos","agilidad505Segundos"] as const;
const measures=["cuelloCm","hombrosCm","pechoCm","brazoCm","antebrazoCm","cinturaCm","abdomenCm","caderaCm","gluteoCm","musloCm","pantorrillaCm"] as const;
const number=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:undefined;
const mean=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:undefined;
const round=(value:number)=>Math.round(value);
const latestMerged=(records:PhysicalAssessment[])=>{const health=records.find(item=>item.tipoRegistro!=="pruebas"),tests=records.find(item=>item.tipoRegistro==="pruebas");return health||tests?{...(health||{}),...(tests||{}),id:(records[0]?.id||""),fecha:(records[0]?.fecha||"")} as PhysicalAssessment:undefined};
const ageBand=(age?:number)=>age===undefined?"edad sin registrar":age<13?"≤12":age<18?"13–17":age<30?"18–29":age<40?"30–39":age<50?"40–49":"50+";
const weightBand=(weight?:number)=>weight===undefined?"peso sin registrar":`${Math.floor(weight/10)*10}–${Math.floor(weight/10)*10+9} kg`;
const percentile=(value:number,pool:number[],inverse=false)=>{if(pool.length<2)return 50;const below=pool.filter(item=>inverse?item>value:item<value).length,equal=pool.filter(item=>item===value).length;return round((below+equal*.5)/pool.length*100)};
function healthScore(record?:PhysicalAssessment){if(!record)return undefined;const scores:number[]=[];if(record.edad!==undefined&&record.edad>=20&&record.imc!==undefined)scores.push(record.imc>=18.5&&record.imc<25?100:record.imc>=17&&record.imc<30?70:record.imc>=15&&record.imc<35?40:15);if(record.cinturaEstatura!==undefined)scores.push(record.cinturaEstatura<.5?100:record.cinturaEstatura<.6?55:20);const fat=healthyBodyFatRange(record.edad,record.sexoCalculo);if(fat&&record.grasaPorcentaje!==undefined){const [low,high]=fat;scores.push(record.grasaPorcentaje>=low&&record.grasaPorcentaje<=high?100:record.grasaPorcentaje>=low-3&&record.grasaPorcentaje<=high+5?65:30)}if(record.calidadMedicion!==undefined)scores.push(record.calidadMedicion);return scores.length?round(mean(scores)!):undefined}
function balanceScore(record?:PhysicalAssessment){if(!record)return undefined;const captured=measures.filter(key=>number(record[key])!==undefined).length,completeness=captured/measures.length*70,context=record.estaturaCm&&record.cinturaCm?Math.max(0,30-Math.max(0,record.cinturaCm/record.estaturaCm-.5)*150):0;return round(completeness+context)}
function improvement(records:PhysicalAssessment[]){const current=latestMerged(records),prior=latestMerged(records.slice(1));if(!current||!prior)return undefined;const changes:number[]=[];higher.forEach(key=>{const a=number(current[key]),b=number(prior[key]);if(a!==undefined&&b&&b>0)changes.push((a-b)/b*100)});lower.forEach(key=>{const a=number(current[key]),b=number(prior[key]);if(a!==undefined&&b&&b>0)changes.push((b-a)/b*100)});return changes.length?round(mean(changes)!*10)/10:undefined}

export function buildAthleteAnalytics(athletes:AnalyticsAthlete[]):AthleteAnalytics[]{const raw=athletes.map(athlete=>{const records=(athlete.historialFisico||[]) as PhysicalAssessment[],latest=latestMerged(records),age=latest?.edad,sex=latest?.sexoCalculo||"sin sexo",weight=latest?.pesoKg,peerKey=`${sex}|${ageBand(age)}|${weightBand(weight)}`;return{athlete,records,latest,peerKey,peerLabel:`${sex} · ${ageBand(age)} años · ${weightBand(weight)}`,improvement:improvement(records)}});const scored=raw.map(item=>{const peers=raw.filter(peer=>peer.peerKey===item.peerKey&&peer.latest),fallback=peers.length>=3?peers:raw.filter(peer=>peer.latest),metricScores:number[]=[];if(item.latest){higher.forEach(key=>{const value=number(item.latest?.[key]);if(value===undefined)return;const pool=fallback.map(peer=>number(peer.latest?.[key])).filter((entry):entry is number=>entry!==undefined);if(pool.length>=2)metricScores.push(percentile(value,pool))});lower.forEach(key=>{const value=number(item.latest?.[key]);if(value===undefined)return;const pool=fallback.map(peer=>number(peer.latest?.[key])).filter((entry):entry is number=>entry!==undefined);if(pool.length>=2)metricScores.push(percentile(value,pool,true))})}const performanceScore=metricScores.length?round(mean(metricScores)!):undefined,health=healthScore(item.latest),balance=balanceScore(item.latest),improvementScore=item.improvement===undefined?undefined:Math.max(0,Math.min(100,round(50+item.improvement*3))),dataQuality=round(([item.latest?.edad,item.latest?.pesoKg,item.latest?.sexoCalculo,...higher.map(key=>item.latest?.[key])].filter(value=>value!==undefined).length/(3+higher.length))*100),strengths:string[]=[],priorities:string[]=[];if(performanceScore!==undefined){if(performanceScore>=70)strengths.push("Rendimiento sobre su grupo comparable");else if(performanceScore<40)priorities.push("Construir una base física más uniforme")};if(health!==undefined){if(health>=80)strengths.push("Indicadores de cribado favorables");else if(health<55)priorities.push("Revisar indicadores de salud y calidad de medición")};if(balance!==undefined){if(balance>=75)strengths.push("Perfil corporal bien documentado");else priorities.push("Completar perímetros para analizar proporciones")};const trend=item.improvement===undefined?"baseline":item.improvement>2?"up":item.improvement< -2?"down":"stable";return{id:item.athlete.id,nombre:item.athlete.nombre,latest:item.latest,healthScore:health,performanceScore,balanceScore:balance,improvementScore,peerLabel:item.peerLabel,peerSize:fallback.length,dataQuality,trend,strengths,priorities} as AthleteAnalytics});const ranked=scored.filter(item=>item.performanceScore!==undefined).sort((a,b)=>(b.performanceScore||0)-(a.performanceScore||0)||(b.improvementScore||0)-(a.improvementScore||0));return scored.map(item=>({...item,performanceRank:ranked.findIndex(entry=>entry.id===item.id)+1||undefined}))}
