"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { collection, doc, getDoc, getDocs, query, serverTimestamp, setDoc, Timestamp, where } from "firebase/firestore";
import { Activity, ArrowRight, BatteryCharging, BookOpenCheck, CalendarCheck, Check, ChevronRight, CircleUserRound, Dumbbell, Flame, Footprints, Gauge, HeartPulse, Loader2, Medal, Moon, Network, ShieldCheck, Sparkles, Target, Trophy } from "lucide-react";
import { useFirestore, useUser } from "@/firebase";
import type { PhysicalAssessment, SkillProgress } from "@/lib/athlete-progress";

type Athlete = {
  id:string; nombre:string; disciplina?:string; grado?:string; fotoUrl?:string; estadoPago?:string;
  objetivo?:string; historialFisico?:PhysicalAssessment[]; habilidadesTecnicas?:SkillProgress;
};
type Checkin = {energia:number;sueno:number;dolor:number;animo:number;fecha:string};
type Attendance = {fecha?:Timestamp};

const today=()=>new Date().toISOString().slice(0,10);
const options={energia:[[1,"Vacío"],[2,"Bajo"],[3,"Normal"],[4,"Bien"],[5,"Excelente"]],sueno:[[1,"Muy mal"],[2,"Poco"],[3,"Regular"],[4,"Bien"],[5,"Profundo"]],dolor:[[0,"Sin dolor"],[1,"Leve"],[2,"Ligero"],[3,"Moderado"],[4,"Alto"],[5,"Muy alto"]],animo:[[1,"Difícil"],[2,"Bajo"],[3,"Estable"],[4,"Bien"],[5,"Excelente"]]} as const;

export function AthleteCommandCenter(){
 const db=useFirestore(),{user}=useUser();const [athlete,setAthlete]=useState<Athlete|null>(null),[attendance,setAttendance]=useState<Attendance[]>([]),[checkin,setCheckin]=useState<Checkin>({energia:3,sueno:3,dolor:0,animo:3,fecha:today()}),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false;void(async()=>{if(!user||!db)return;setLoading(true);try{const profile=await getDoc(doc(db,"usuarios",user.uid)),studentId=String(profile.data()?.alumnoId||"");if(!studentId)throw new Error("Tu cuenta todavía no está vinculada con un expediente de atleta.");const [student,att,wellness]=await Promise.all([getDoc(doc(db,"Alumnos",studentId)),getDocs(query(collection(db,"Asistencias"),where("alumnoId","==",studentId))),getDoc(doc(db,"BienestarAtletas",`${user.uid}_${today()}`))]);if(!student.exists())throw new Error("No encontramos tu expediente de atleta.");if(cancelled)return;setAthlete({id:student.id,...student.data()} as Athlete);setAttendance(att.docs.map(item=>item.data() as Attendance));if(wellness.exists()){const data=wellness.data();setCheckin({energia:Number(data.energia||3),sueno:Number(data.sueno||3),dolor:Number(data.dolor||0),animo:Number(data.animo||3),fecha:today()});setSaved(true)}}catch(reason){if(!cancelled)setError(reason instanceof Error?reason.message:"No pudimos cargar tu centro personal.")}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[db,user]);
 const insights=useMemo(()=>{const dates=attendance.map(item=>item.fecha?.toDate()).filter((date):date is Date=>Boolean(date)),monthAgo=Date.now()-30*86400000,month=dates.filter(date=>date.getTime()>=monthAgo).length,total=new Set(dates.map(date=>date.toISOString().slice(0,10))).size,latest=[...(athlete?.historialFisico||[])].sort((a,b)=>b.fecha.localeCompare(a.fecha))[0],skills=Object.values(athlete?.habilidadesTecnicas||{}),mastered=skills.filter(value=>value==="dominada").length,practicing=skills.filter(value=>value==="practicando").length;return {month,total,latest,mastered,practicing}},[attendance,athlete]);
 const readiness=Math.max(0,Math.min(100,Math.round((checkin.energia+checkin.sueno+checkin.animo+(5-checkin.dolor))*5)));
 const coach=checkin.dolor>=4?"Hoy conviene evitar intensidad y avisar al profesor sobre el dolor antes de entrenar.":readiness<55?"Prioriza técnica suave, hidratación y recuperación. No necesitas forzar una sesión difícil.":insights.month<6?"Tu recuperación permite entrenar. El objetivo de esta semana es recuperar constancia con una clase más.":"Vas con buena constancia. Aprovecha la sesión para consolidar una habilidad que ya estás practicando.";
 async function saveCheckin(){if(!db||!user||!athlete)return;setSaving(true);setError("");try{await setDoc(doc(db,"BienestarAtletas",`${user.uid}_${today()}`),{...checkin,alumnoId:athlete.id,usuarioId:user.uid,sede:(athlete as Athlete&{sede?:string}).sede||"",actualizadoEn:serverTimestamp()},{merge:true});setSaved(true)}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo guardar tu check-in.")}finally{setSaving(false)}}
 if(loading)return <main className="grid min-h-[75vh] place-items-center bg-[#08090c]"><Loader2 className="h-8 w-8 animate-spin text-amber-300"/></main>;
 if(error&&!athlete)return <main className="min-h-screen bg-[#08090c] p-5 text-white"><div className="mx-auto mt-20 max-w-lg rounded-3xl border border-red-300/20 bg-red-500/10 p-6 text-center"><HeartPulse className="mx-auto h-10 w-10 text-red-300"/><h1 className="mt-3 text-xl font-black">No pudimos abrir tu centro</h1><p className="mt-2 text-sm text-red-100/80">{error}</p></div></main>;
 return <main className="min-h-screen bg-[#08090c] pb-24 text-white md:pb-10"><div className="mx-auto max-w-[1500px] space-y-6 p-4 sm:p-6 lg:p-8">
  <header className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_80%_0%,rgba(251,191,36,.16),transparent_34%),linear-gradient(135deg,#17191f,#0d0e12)] p-5 shadow-2xl sm:p-7"><div className="absolute -right-14 -top-16 h-48 w-48 rounded-full border-[28px] border-amber-300/[.06]"/><div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.22em] text-amber-300">Centro del atleta</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-5xl">Hola, {athlete?.nombre?.split(" ")[0]}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-400">Todo lo importante de tu entrenamiento, bienestar y progreso en una sola vista.</p><div className="mt-4 flex flex-wrap gap-2"><Tag icon={ShieldCheck} text={athlete?.disciplina||"Disciplina pendiente"}/><Tag icon={Medal} text={athlete?.grado||"Grado pendiente"}/><Tag icon={Target} text={athlete?.objetivo||"Define tu objetivo"}/></div></div><div className="grid grid-cols-3 gap-2 sm:min-w-[390px]"><HeroStat value={insights.month} label="Clases · 30 días"/><HeroStat value={insights.mastered} label="Dominadas"/><HeroStat value={readiness} label="Preparación" suffix="%"/></div></div></header>
  <section className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><article className="rounded-[2rem] border border-white/10 bg-[#12141a] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Check-in diario</p><h2 className="mt-1 text-2xl font-black">¿Cómo llegas hoy?</h2><p className="mt-1 text-sm text-slate-400">Tarda menos de 20 segundos y mejora tus recomendaciones.</p></div><div className={`rounded-full px-3 py-1.5 text-xs font-black ${readiness>=75?'bg-emerald-400/15 text-emerald-200':readiness>=50?'bg-amber-400/15 text-amber-200':'bg-red-400/15 text-red-200'}`}>{readiness}% preparado</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{(["energia","sueno","dolor","animo"] as const).map(key=><WellnessPicker key={key} name={key} value={checkin[key]} onChange={value=>{setCheckin(current=>({...current,[key]:value}));setSaved(false)}}/>)}</div>{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<button onClick={()=>void saveCheckin()} disabled={saving||saved} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-emerald-400 px-5 font-black text-slate-950 transition hover:bg-emerald-300 disabled:bg-white/10 disabled:text-slate-400">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:saved?<Check className="h-4 w-4"/>:<HeartPulse className="h-4 w-4"/>}{saving?"Guardando…":saved?"Check-in guardado":"Guardar cómo me siento"}</button></article>
   <article className="relative overflow-hidden rounded-[2rem] border border-amber-300/15 bg-[linear-gradient(145deg,rgba(251,191,36,.13),rgba(255,255,255,.025))] p-5 sm:p-6"><Sparkles className="absolute right-5 top-5 h-7 w-7 text-amber-300"/><p className="text-xs font-black uppercase tracking-[.18em] text-amber-300">Coach semanal</p><h2 className="mt-2 pr-10 text-2xl font-black">Tu siguiente mejor paso</h2><p className="mt-4 text-base font-semibold leading-7 text-slate-200">{coach}</p><div className="mt-6 rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Misión recomendada</p><p className="mt-1 font-bold">{insights.practicing?"Practica una habilidad marcada como en progreso.":"Completa una clase y revisa tu árbol técnico."}</p></div><Link href="/habilidades" className="mt-5 inline-flex items-center gap-2 text-sm font-black text-amber-200">Abrir mi árbol <ArrowRight className="h-4 w-4"/></Link></article>
  </section>
  <section><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-slate-500">Resumen personal</p><h2 className="text-2xl font-black">Tu progreso</h2></div><Link href="/mi-academia" className="text-sm font-bold text-amber-200">Ver expediente</Link></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Flame} label="Asistencias históricas" value={String(insights.total)} detail={`${insights.month} en los últimos 30 días`} tone="text-orange-300"/><Metric icon={Network} label="Progreso técnico" value={`${insights.mastered} dominadas`} detail={`${insights.practicing} en práctica`} tone="text-violet-300"/><Metric icon={Gauge} label="Estado físico" value={insights.latest?.imc?`IMC ${insights.latest.imc}`:"Sin evaluación"} detail={insights.latest?`${insights.latest.pesoKg} kg · ${insights.latest.estaturaCm} cm`:"Solicita una evaluación"} tone="text-cyan-300"/><Metric icon={Trophy} label="Cuenta" value={athlete?.estadoPago||"Sin estado"} detail={athlete?.objetivo||"Agrega un objetivo personal"} tone="text-emerald-300"/></div></section>
  <section><div className="mb-3"><p className="text-xs font-black uppercase tracking-[.18em] text-slate-500">Accesos directos</p><h2 className="text-2xl font-black">Continúa tu entrenamiento</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><Quick href="/mi-academia" icon={ShieldCheck} label="Mi Academia" detail="Asistencia y pagos"/><Quick href="/reservas" icon={CalendarCheck} label="Reservar" detail="Aparta tu clase"/><Quick href="/habilidades" icon={Network} label="Habilidades" detail="Árbol técnico"/><Quick href="/estado-fisico" icon={Activity} label="Estado físico" detail="Medidas y pruebas"/><Quick href="/bitacora" icon={BookOpenCheck} label="Bitácora" detail="Registra tu día"/><Quick href="/recompensas" icon={Trophy} label="Recompensas" detail="Logros y beneficios"/></div></section>
 </div></main>
}

function WellnessPicker({name,value,onChange}:{name:keyof typeof options;value:number;onChange:(value:number)=>void}){const labels={energia:[BatteryCharging,"Energía"],sueno:[Moon,"Sueño"],dolor:[HeartPulse,"Dolor"],animo:[CircleUserRound,"Ánimo"]} as const,Icon=labels[name][0];return <fieldset className="rounded-2xl border border-white/[.08] bg-black/20 p-3"><legend className="sr-only">{labels[name][1]}</legend><div className="mb-3 flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-black"><Icon className="h-4 w-4 text-emerald-300"/>{labels[name][1]}</span><b className="text-xs text-slate-400">{options[name].find(option=>option[0]===value)?.[1]}</b></div><div className={`grid gap-1 ${name==='dolor'?'grid-cols-6':'grid-cols-5'}`}>{options[name].map(([number])=><button key={number} type="button" onClick={()=>onChange(number)} aria-label={`${labels[name][1]} ${number}`} aria-pressed={value===number} className={`h-9 rounded-lg text-xs font-black transition ${value===number?'bg-emerald-400 text-slate-950':'bg-white/[.05] text-slate-500 hover:bg-white/10 hover:text-white'}`}>{number}</button>)}</div></fieldset>}
function Tag({icon:Icon,text}:{icon:typeof ShieldCheck;text:string}){return <span className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[.05] px-3 py-1.5 text-xs font-bold text-slate-300"><Icon className="h-3.5 w-3.5 text-amber-300"/>{text}</span>}
function HeroStat({value,label,suffix=""}:{value:number;label:string;suffix?:string}){return <div className="rounded-2xl border border-white/10 bg-black/25 p-3 text-center"><b className="block text-2xl tabular-nums text-white sm:text-3xl">{value}{suffix}</b><span className="mt-1 block text-[9px] font-black uppercase leading-4 tracking-wider text-slate-500">{label}</span></div>}
function Metric({icon:Icon,label,value,detail,tone}:{icon:typeof Footprints;label:string;value:string;detail:string;tone:string}){return <article className="rounded-3xl border border-white/10 bg-[#12141a] p-5"><Icon className={`h-6 w-6 ${tone}`}/><p className="mt-4 text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><b className="mt-1 block text-xl text-white">{value}</b><p className="mt-1 truncate text-xs text-slate-400">{detail}</p></article>}
function Quick({href,icon:Icon,label,detail}:{href:string;icon:typeof Dumbbell;label:string;detail:string}){return <Link href={href} className="group flex min-h-32 flex-col rounded-3xl border border-white/10 bg-white/[.035] p-4 transition hover:-translate-y-1 hover:border-amber-300/25 hover:bg-amber-300/[.06]"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/[.07] text-amber-300"><Icon className="h-5 w-5"/></span><ChevronRight className="h-4 w-4 text-slate-600 transition group-hover:translate-x-1 group-hover:text-amber-300"/></div><b className="mt-auto text-sm text-white">{label}</b><span className="text-xs text-slate-500">{detail}</span></Link>}
