"use client";

import { useEffect, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { CalendarClock, CheckCircle2, Loader2, MapPin, QrCode, ShieldCheck, TicketCheck } from "lucide-react";

type PublicPass = { id: string; guestName: string; discipline: string; hostName: string; site: string; uses: number; maxUses: number; remaining: number; validFrom: string | null; validUntil: string | null; status: "valid" | "scheduled" | "expired" | "used" | "revoked" };
function deviceId() { const key = "albatros-guest-pass-device"; let value = window.localStorage.getItem(key); if (!value) { value = window.crypto.randomUUID(); window.localStorage.setItem(key, value); } return value; }
const labels = { valid: "Pase válido", scheduled: "Todavía no inicia", expired: "Pase vencido", used: "Entradas agotadas", revoked: "Pase revocado" } as const;

export default function GuestPassPage() {
  const { id } = useParams<{ id: string }>(); const search = useSearchParams(); const [token] = useState(() => search.get("token") || ""); const [pass, setPass] = useState<PublicPass | null>(null); const [message, setMessage] = useState("Cargando pase…"); const [checking, setChecking] = useState(false); const [registered, setRegistered] = useState<{ remaining: number } | null>(null);
  useEffect(() => { if (!id || !token) { setMessage("El enlace del pase está incompleto."); return; } void fetch(`/api/pases-invitados/${id}?token=${encodeURIComponent(token)}`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setPass(data.pass); setMessage(""); window.history.replaceState({}, "", window.location.pathname); }).catch((error) => setMessage(error instanceof Error ? error.message : "No se pudo abrir el pase.")); }, [id, token]);
  async function checkIn() { if (!pass || !window.confirm("¿Registrar tu entrada ahora?")) return; setChecking(true); setMessage(""); try { const response = await fetch(`/api/pases-invitados/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, deviceId: deviceId() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setRegistered({ remaining: data.remaining }); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo registrar."); } finally { setChecking(false); } }
  if (registered) return <main className="grid min-h-screen place-items-center bg-[#08090c] p-6 text-white"><div className="max-w-lg rounded-3xl border border-emerald-400/25 bg-[#101a16] p-8 text-center"><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-400" /><h1 className="mt-4 text-3xl font-black text-white">Entrada registrada</h1><p className="mt-2 text-white/60">Bienvenido a Albatros, {pass?.guestName}.</p><p className="mt-4 rounded-xl bg-black/20 px-4 py-3 font-black text-white">Entradas restantes: {registered.remaining}</p></div></main>;
  if (!pass) return <main className="grid min-h-screen place-items-center bg-[#08090c] p-6 text-white"><div className="max-w-md rounded-3xl border border-white/10 bg-[#17181d] p-8 text-center">{message === "Cargando pase…" && <Loader2 className="mx-auto mb-4 h-10 w-10 animate-spin text-emerald-400" />}<p className="font-black text-white">{message}</p></div></main>;
  const valid = pass.status === "valid";
  return <main className="min-h-screen bg-[#08090c] px-4 py-8 text-white"><div className="mx-auto max-w-xl overflow-hidden rounded-[2rem] border border-white/10 bg-[#17181d] shadow-2xl"><header className={`p-6 text-center ${valid ? "bg-emerald-400 text-[#06110c]" : "bg-red-500 text-white"}`}><TicketCheck className="mx-auto h-12 w-12" /><p className="mt-2 text-xs font-black uppercase tracking-[.2em]">Pase de invitado</p><h1 className="mt-1 text-3xl font-black">{labels[pass.status]}</h1></header><div className="grid gap-5 p-6"><div className="text-center"><p className="text-sm font-black uppercase tracking-wide text-white/70">Invitado</p><h2 className="text-4xl font-black text-white">{pass.guestName}</h2><p className="mt-1 text-lg font-bold text-emerald-300">{pass.discipline}</p></div><div className="grid grid-cols-2 gap-3"><Info icon={MapPin} label="Sede" value={pass.site} /><Info icon={ShieldCheck} label="Invitado por" value={pass.hostName || "Albatros"} /><Info icon={CalendarClock} label="Válido hasta" value={pass.validUntil ? new Date(pass.validUntil).toLocaleString("es-MX") : "—"} /><Info icon={QrCode} label="Entradas" value={`${pass.remaining} de ${pass.maxUses}`} /></div>{message && <p className="rounded-xl border border-amber-300/20 bg-amber-300/10 px-4 py-3 text-sm font-bold text-amber-100">{message}</p>}{valid ? <><p className="text-center text-sm text-white/70">Muestra esta pantalla en recepción o registra la entrada cuando estés físicamente en la academia.</p><button type="button" disabled={checking} onClick={checkIn} className="h-14 rounded-xl bg-emerald-400 text-lg font-black text-[#06110c] disabled:opacity-60">{checking ? "Registrando…" : "Registrar entrada ahora"}</button></> : <p className="rounded-xl bg-black/20 p-4 text-center font-bold text-white/60">Solicita un pase nuevo en recepción.</p>}</div></div></main>;
}
function Info({ icon: Icon, label, value }: { icon: typeof MapPin; label: string; value: string }) { return <div className="rounded-xl bg-black/25 p-3"><Icon className="h-4 w-4 text-emerald-300" /><p className="mt-2 text-xs font-black uppercase text-white/70">{label}</p><p className="font-bold text-white">{value}</p></div>; }
