"use client";

import { useCallback, useEffect, useState } from "react";
import { Loader2, RefreshCw, Wifi, WifiOff } from "lucide-react";
import { useParams, useSearchParams } from "next/navigation";

import { GrapplingChessBoard } from "@/components/grappling-chess-board";
import type { GrapplingChessMove, GrapplingChessState } from "@/lib/grappling-chess";

type RemoteState = GrapplingChessState & { viewer: 0 | 1; legalMoves: GrapplingChessMove[] };

export default function OnlineGrapplingChessPage() {
  const params = useParams<{ code: string }>(); const search = useSearchParams(); const token = search.get("token") || ""; const code = String(params.code || "").toUpperCase();
  const [state, setState] = useState<RemoteState | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("Conectando con la partida…"); const [online, setOnline] = useState(true);
  const load = useCallback(async (quiet = false) => { if (!code || !token) { setMessage("La invitación está incompleta."); setLoading(false); return; } try { const response = await fetch(`/api/ajedrez/${encodeURIComponent(code)}?token=${encodeURIComponent(token)}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setState(data.state); setOnline(true); if (!quiet) setMessage(""); } catch (error) { setOnline(false); if (!quiet) setMessage(error instanceof Error ? error.message : "No se pudo actualizar la partida."); } finally { setLoading(false); } }, [code, token]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!state || state.winner !== null || state.turn === state.viewer) return; const timer = window.setInterval(() => { if (document.visibilityState === "visible" && !busy) void load(true); }, 7000); return () => window.clearInterval(timer); }, [busy, load, state]);
  async function move(moveId: string) { if (!state || state.turn !== state.viewer) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/ajedrez/${encodeURIComponent(code)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, moveId, revision: state.revision }) }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setState(data.state); setOnline(true); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo guardar el movimiento."); await load(true); } finally { setBusy(false); } }
  if (loading && !state) return <main className="grid min-h-screen place-items-center bg-[#07090d] p-6 text-white"><div className="text-center"><Loader2 className="mx-auto h-10 w-10 animate-spin text-red-400" /><p className="mt-4 font-black">{message}</p></div></main>;
  if (!state) return <main className="grid min-h-screen place-items-center bg-[#07090d] p-6 text-white"><div className="max-w-md rounded-3xl border border-red-400/20 bg-red-500/10 p-8 text-center"><WifiOff className="mx-auto h-10 w-10 text-red-300" /><h1 className="mt-4 text-2xl font-black">No se pudo abrir la partida</h1><p className="mt-2 text-white/60">{message}</p><button onClick={() => void load()} className="mt-5 h-11 rounded-xl bg-white px-5 font-black text-black">Intentar otra vez</button></div></main>;
  const yourTurn = state.turn === state.viewer && state.winner === null;
  return <main className="min-h-screen bg-[#07090d] p-3 text-white sm:p-6"><div className="mx-auto max-w-[1500px] space-y-4"><header className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-[#12141a] p-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-red-300">Ajedrez de combate · Sala {code}</p><h1 className="mt-1 text-xl font-black sm:text-3xl">Juegas como {state.players[state.viewer]}</h1></div><div className="flex items-center gap-2"><span className={`inline-flex items-center gap-2 rounded-full border px-3 py-2 text-xs font-black ${online ? "border-emerald-300/20 bg-emerald-400/10 text-emerald-200" : "border-amber-300/20 bg-amber-400/10 text-amber-200"}`}>{online ? <Wifi className="h-4 w-4" /> : <WifiOff className="h-4 w-4" />}{online ? "Sincronizado" : "Reconectando"}</span><button type="button" onClick={() => void load()} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10" aria-label="Actualizar"><RefreshCw className="h-4 w-4" /></button></div></header>{message && <p className="rounded-xl border border-amber-300/20 bg-amber-400/10 px-4 py-3 text-sm font-bold text-amber-100">{message}</p>}<p className={`rounded-xl px-4 py-3 text-center text-sm font-black ${yourTurn ? "bg-red-500 text-white" : "border border-white/10 bg-white/[.04] text-white/55"}`}>{state.winner !== null ? `Ganó ${state.players[state.winner]}` : yourTurn ? "Es tu turno: elige un movimiento" : `Espera a ${state.players[state.turn]}`}</p><GrapplingChessBoard state={state} moves={yourTurn ? state.legalMoves : []} onMove={move} busy={busy} online /></div></main>;
}
