"use client";
import Link from "next/link";
import { useCallback,useEffect,useRef,useState } from "react";
import { ArrowLeft,BrainCircuit,Maximize2,Pause,Play,RotateCcw,Volume2,VolumeX } from "lucide-react";
const stimuli=[{n:1,c:"ROJO",bg:"bg-red-500",action:"JAB"},{n:2,c:"AZUL",bg:"bg-blue-500",action:"CROSS"},{n:3,c:"VERDE",bg:"bg-emerald-500",action:"ESQUIVA"},{n:4,c:"AMARILLO",bg:"bg-amber-300",action:"SPRAWL"}];
type Stimulus=typeof stimuli[number];
export default function ReactionPage(){const [duration,setDuration]=useState(60),[delay,setDelay]=useState(2),[sound,setSound]=useState(true),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[left,setLeft]=useState(60),[item,setItem]=useState<Stimulus|null>(null),[hits,setHits]=useState(0),[errors,setErrors]=useState(0),[times,setTimes]=useState<number[]>([]),[full,setFull]=useState(false);const shown=useRef(0),timer=useRef<ReturnType<typeof setInterval>|null>(null),next=useRef<ReturnType<typeof setTimeout>|null>(null);
 const tone=useCallback((ok=true)=>{if(!sound)return;const C=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?900:190;g.gain.value=.1;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.1)},[sound]);
 const show=useCallback(()=>{const x=stimuli[Math.floor(Math.random()*stimuli.length)];shown.current=performance.now();setItem(x)},[]);
 function clear(){if(timer.current)clearInterval(timer.current);if(next.current)clearTimeout(next.current)}
 function start(){clear();setHits(0);setErrors(0);setTimes([]);setLeft(duration);setRunning(true);setPaused(false);show();timer.current=setInterval(()=>setLeft(v=>{if(v<=1){clear();setRunning(false);setItem(null);return 0}return v-1}),1000)}
 function answer(n:number){if(!running||paused||!item)return;if(n===item.n){setHits(v=>v+1);setTimes(v=>[...v,Math.round(performance.now()-shown.current)]);tone(true);setItem(null);next.current=setTimeout(show,delay*1000)}else{setErrors(v=>v+1);tone(false)}}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const n=Number(e.key);if(n>=1&&n<=4)answer(n)};window.addEventListener("keydown",key);return()=>{clear();window.removeEventListener("keydown",key)} });
 const avg=times.length?Math.round(times.reduce((a,b)=>a+b,0)/times.length):0,best=times.length?Math.min(...times):0;
 function togglePause(){if(paused){setPaused(false);if(!item)show();timer.current=setInterval(()=>setLeft(v=>{if(v<=1){clear();setRunning(false);setItem(null);return 0}return v-1}),1000)}else{clear();setPaused(true)}}
 return <main className="min-h-screen bg-[#070a08] p-4 text-white sm:p-7"><div className="mx-auto max-w-7xl space-y-5"><Header back="Puzzle 05" title="Reacción por colores y números"/><section className="grid gap-4 lg:grid-cols-[320px_1fr]"><aside className="space-y-4 rounded-3xl border border-white/10 bg-white/[.04] p-5"><Field label="Duración"><Select value={duration} set={setDuration} values={[30,60,120]}/></Field><Field label="Espera entre estímulos"><Select value={delay} set={setDelay} values={[1,2,3]}/></Field><button onClick={()=>setSound(!sound)} className="ctl">{sound?<Volume2/>:<VolumeX/>} Sonido {sound?"activo":"silenciado"}</button><button onClick={start} className="primary"><Play/>Iniciar prueba</button><button onClick={()=>{clear();setRunning(false);setItem(null);setLeft(duration)}} className="ctl"><RotateCcw/>Reiniciar</button></aside><section className={`relative grid min-h-[600px] place-items-center overflow-hidden rounded-[2rem] border border-white/10 bg-[#101410] p-5 text-center ${full?'fixed inset-0 z-50 rounded-none':''}`} onClick={()=>item&&answer(item.n)}>{full&&<button onClick={e=>{e.stopPropagation();setFull(false)}} className="absolute right-5 top-5 z-10 ctl">Salir</button>}<button onClick={e=>{e.stopPropagation();setFull(true)}} className="absolute left-5 top-5 ctl"><Maximize2/>Pantalla</button><b className="absolute right-6 top-6 font-mono text-3xl">{left}s</b>{item?<div><div className={`mx-auto grid h-56 w-56 place-items-center rounded-[3rem] ${item.bg} text-[9rem] font-black text-white shadow-2xl sm:h-80 sm:w-80`}>{item.n}</div><h2 className="mt-7 text-5xl font-black sm:text-8xl">{item.c}</h2><p className="mt-3 text-2xl font-black text-white/60">{item.action}</p></div>:running?<p className="text-4xl font-black text-white/30">PREPÁRATE…</p>:<div><BrainCircuit className="mx-auto h-28 w-28 text-lime-300/30"/><h2 className="mt-4 text-5xl font-black">LISTO PARA REACCIONAR</h2><p className="mt-3 text-white/50">Pulsa 1–4 o toca el estímulo correcto.</p></div>}</section></section><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat l="Aciertos" v={hits}/><Stat l="Errores" v={errors}/><Stat l="Promedio" v={avg?`${avg} ms`:"—"}/><Stat l="Récord" v={best?`${best} ms`:"—"}/></div>{running&&<button onClick={togglePause} className="primary mx-auto"><Pause/>{paused?"Continuar":"Pausar"}</button>}</div></main>}
function Header({back,title}:{back:string;title:string}){return <header className="rounded-[2rem] border border-lime-300/15 bg-gradient-to-br from-lime-500/15 to-transparent p-6"><Link href="/admin/puzzle" className="flex items-center gap-2 text-xs font-black text-lime-300"><ArrowLeft className="h-4 w-4"/>PUZZLE HUB</Link><p className="mt-5 text-xs font-black uppercase tracking-widest text-lime-300">{back}</p><h1 className="mt-2 text-4xl font-black sm:text-6xl">{title}</h1></header>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><p className="mb-2 text-xs font-black uppercase text-white/50">{label}</p>{children}</div>};function Select({value,set,values}:{value:number;set:(n:number)=>void;values:number[]}){return <div className="grid grid-cols-3 gap-2">{values.map(v=><button key={v} onClick={()=>set(v)} className={value===v?"primary":"ctl"}>{v}s</button>)}</div>};function Stat({l,v}:{l:string;v:string|number}){return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-4 text-center"><p className="text-xs font-black uppercase text-white/40">{l}</p><b className="mt-1 block text-3xl">{v}</b></div>}
