"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, AudioLines, Check, Dumbbell, Maximize2, Minimize2, Pause, Play, RefreshCw, Repeat2, RotateCcw, Shield, SkipForward, Timer, UsersRound, Volume2, VolumeX } from "lucide-react";

type Family="boxeo"|"patadas"|"defensa";
type Combination={id:string;name:string;steps:string[];numbers:string;family:Family;response:string};
type Speed="tecnica"|"fluida"|"intensa";
type Side="A"|"B";

const combinations:Combination[]=[
 {id:"jab-cross",name:"Jab · Cross",steps:["JAB","CROSS"],numbers:"1 — 2",family:"boxeo",response:"Guardia firme y recepción con manoplas"},
 {id:"jab-cross-hook",name:"Jab · Cross · Hook",steps:["JAB","CROSS","HOOK"],numbers:"1 — 2 — 3",family:"boxeo",response:"Bloquea rectos y cubre el hook"},
 {id:"cross-hook-cross",name:"Cross · Hook · Cross",steps:["CROSS","HOOK","CROSS"],numbers:"2 — 3 — 2",family:"boxeo",response:"Marca objetivos y recupera guardia"},
 {id:"jab-body-cross",name:"Jab · Cuerpo · Cross",steps:["JAB","GANCHO AL CUERPO","CROSS"],numbers:"1 — B — 2",family:"boxeo",response:"Protege cabeza, cuerpo y vuelve al centro"},
 {id:"jab-cross-low",name:"Jab · Cross · Low kick",steps:["JAB","CROSS","LOW KICK"],numbers:"1 — 2 — LK",family:"patadas",response:"Recibe manos y chequea la low kick"},
 {id:"jab-teep-cross",name:"Jab · Teep · Cross",steps:["JAB","TEEP","CROSS"],numbers:"1 — T — 2",family:"patadas",response:"Controla distancia y presenta objetivo"},
 {id:"cross-hook-middle",name:"Cross · Hook · Patada media",steps:["CROSS","HOOK","MIDDLE KICK"],numbers:"2 — 3 — MK",family:"patadas",response:"Cubre manos y recibe la patada con protección"},
 {id:"jab-slip-cross",name:"Jab · Slip · Cross",steps:["JAB","SLIP","CROSS"],numbers:"1 — S — 2",family:"defensa",response:"Lanza jab controlado para provocar el slip"},
 {id:"cross-roll-hook",name:"Cross · Roll · Hook",steps:["CROSS","ROLL","HOOK"],numbers:"2 — R — 3",family:"defensa",response:"Marca cross y hook amplios sin contacto fuerte"},
 {id:"jab-cross-sprawl",name:"Jab · Cross · Sprawl",steps:["JAB","CROSS","SPRAWL"],numbers:"1 — 2 — SP",family:"defensa",response:"Da señal visual de entrada después del cross"},
];
const speeds:Record<Speed,{label:string;interval:number;detail:string}>={tecnica:{label:"Técnica",interval:3200,detail:"Control y corrección"},fluida:{label:"Fluida",interval:2300,detail:"Ritmo continuo"},intensa:{label:"Intensa",interval:1500,detail:"Reacción rápida"}};

export default function PairPuzzlePage(){
 const [speed,setSpeed]=useState<Speed>("fluida"),[duration,setDuration]=useState(120),[reps,setReps]=useState(3),[families,setFamilies]=useState<Record<Family,boolean>>({boxeo:true,patadas:true,defensa:true}),[sound,setSound]=useState(true),[voice,setVoice]=useState(false),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[presentation,setPresentation]=useState(false),[remaining,setRemaining]=useState(120),[countdown,setCountdown]=useState(0),[activeSide,setActiveSide]=useState<Side>("A"),[current,setCurrent]=useState<Combination|null>(null),[rep,setRep]=useState(0),[series,setSeries]=useState(0),[totalReps,setTotalReps]=useState(0),[progress,setProgress]=useState(0);const timerRef=useRef<ReturnType<typeof setInterval>|null>(null),repRef=useRef<ReturnType<typeof setInterval>|null>(null),introRef=useRef<ReturnType<typeof setInterval>|null>(null),lastRef=useRef(""),repValue=useRef(0),seriesValue=useRef(0),sideRef=useRef<Side>("A"),wakeRef=useRef<{release:()=>Promise<void>}|null>(null);
 const enabled=useMemo(()=>combinations.filter(combo=>families[combo.family]),[families]);
 const clearTimers=useCallback(()=>{if(timerRef.current)clearInterval(timerRef.current);if(repRef.current)clearInterval(repRef.current);if(introRef.current)clearInterval(introRef.current);timerRef.current=null;repRef.current=null;introRef.current=null},[]);
 const tones=useCallback((count:number,frequency=760)=>{if(!sound)return;try{const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext,ctx=new AudioContextClass();for(let index=0;index<count;index++){const osc=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+index*.16;osc.frequency.value=frequency+(index*70);gain.gain.setValueAtTime(.001,start);gain.gain.exponentialRampToValueAtTime(.12,start+.015);gain.gain.exponentialRampToValueAtTime(.001,start+.11);osc.connect(gain);gain.connect(ctx.destination);osc.start(start);osc.stop(start+.12);if(index===count-1)osc.onended=()=>void ctx.close()}}catch{/* La sesión continúa aunque el navegador bloquee el audio. */}},[sound]);
 const speak=useCallback((text:string)=>{if(!voice||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const message=new SpeechSynthesisUtterance(text);message.lang="es-MX";message.rate=1.3;window.speechSynthesis.speak(message)},[voice]);
 const pickCombo=useCallback(()=>{let pool=enabled.filter(combo=>combo.id!==lastRef.current);if(!pool.length)pool=enabled;const combo=pool[Math.floor(Math.random()*pool.length)];lastRef.current=combo.id;setCurrent(combo);return combo},[enabled]);
 const changeRoles=useCallback(()=>{const next:Side=sideRef.current==="A"?"B":"A";sideRef.current=next;setActiveSide(next);seriesValue.current=0;setSeries(0);const combo=pickCombo();tones(3,940);speak(`Cambio. Lado ${next} ataca. ${combo.name}`)},[pickCombo,speak,tones]);
 const performRep=useCallback(()=>{repValue.current+=1;setRep(repValue.current);setTotalReps(value=>value+1);tones(1);if(repValue.current>=reps){repValue.current=0;setRep(0);seriesValue.current+=1;setSeries(seriesValue.current);if(seriesValue.current>=2){window.setTimeout(changeRoles,180)}else{const combo=pickCombo();tones(2,820);speak(combo.name)}}},[changeRoles,pickCombo,reps,speak,tones]);
 const finish=useCallback(()=>{clearTimers();setRunning(false);setPaused(false);setCurrent(null);setProgress(100);window.speechSynthesis?.cancel();void wakeRef.current?.release().catch(()=>undefined);wakeRef.current=null},[clearTimers]);
 const beginTimers=useCallback(()=>{clearTimers();const combo=pickCombo();tones(2,820);speak(`Lado ${sideRef.current}. ${combo.name}`);repRef.current=setInterval(performRep,speeds[speed].interval);timerRef.current=setInterval(()=>setRemaining(value=>{const next=value-1;setProgress(((duration-next)/duration)*100);if(next<=0){queueMicrotask(finish);return 0}return next}),1000)},[clearTimers,duration,finish,performRep,pickCombo,speak,speed,tones]);
 async function start(){if(!enabled.length)return;clearTimers();sideRef.current="A";repValue.current=0;seriesValue.current=0;setActiveSide("A");setRep(0);setSeries(0);setTotalReps(0);setRemaining(duration);setProgress(0);setPaused(false);setRunning(true);setCurrent(null);setCountdown(3);if("wakeLock" in navigator){try{wakeRef.current=await navigator.wakeLock.request("screen")}catch{/* Wake Lock es opcional. */}}let value=3;introRef.current=setInterval(()=>{value-=1;setCountdown(value);tones(1,600+(3-value)*100);if(value<=0){if(introRef.current)clearInterval(introRef.current);introRef.current=null;beginTimers()}},1000)}
 function pause(){if(!running)return;if(paused){setPaused(false);beginTimers()}else{clearTimers();setPaused(true);window.speechSynthesis?.cancel()}}
 function reset(){clearTimers();setRunning(false);setPaused(false);setCountdown(0);setRemaining(duration);setProgress(0);setCurrent(null);setRep(0);setSeries(0);setTotalReps(0);sideRef.current="A";setActiveSide("A");window.speechSynthesis?.cancel();void wakeRef.current?.release().catch(()=>undefined);wakeRef.current=null}
 async function openScreen(){setPresentation(true);try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch{/* La capa de presentación sigue disponible. */}}
 async function closeScreen(){setPresentation(false);try{if(document.fullscreenElement)await document.exitFullscreen()}catch{/* La capa visual se cierra igualmente. */}}
 useEffect(()=>{if(!running)setRemaining(duration)},[duration,running]);useEffect(()=>()=>{clearTimers();window.speechSynthesis?.cancel();void wakeRef.current?.release().catch(()=>undefined)},[clearTimers]);
 const clock=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,"0")}`;
 return <main className="min-h-screen bg-[#07090d] p-4 text-white sm:p-6 lg:p-8"><div className="mx-auto max-w-[1600px] space-y-6"><header className="overflow-hidden rounded-[2.25rem] border border-white/10 bg-[radial-gradient(circle_at_85%_0%,rgba(34,211,238,.2),transparent_36%),linear-gradient(135deg,#0b1a20,#0a0c11_65%)] p-6 shadow-2xl sm:p-8"><Link href="/admin/puzzle" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-cyan-300"><ArrowLeft className="h-4 w-4"/>Biblioteca Puzzle</Link><div className="mt-5 flex flex-col justify-between gap-6 xl:flex-row xl:items-end"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-cyan-300"><UsersRound className="h-4 w-4"/> Puzzle 02</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-5xl">Combinaciones por parejas</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300 sm:text-base">El lado activo ejecuta la combinación al escuchar el pitido. Dos pitidos cambian la combinación y tres intercambian los roles.</p></div><button onClick={()=>void openScreen()} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-cyan-400 px-6 font-black text-cyan-950"><Maximize2/>Pantalla para alumnos</button></div></header>
 <section className="grid gap-5 xl:grid-cols-[420px_1fr]"><aside className="space-y-4 rounded-[2rem] border border-white/10 bg-[#11141a] p-5"><Config title="Velocidad" icon={RefreshCw}><div className="grid grid-cols-3 gap-2">{(Object.keys(speeds) as Speed[]).map(key=><button key={key} disabled={running} onClick={()=>setSpeed(key)} className={`min-h-20 rounded-xl border p-2 text-xs font-black disabled:opacity-40 ${speed===key?'border-cyan-300/35 bg-cyan-500/15 text-cyan-200':'border-white/10 bg-black/20 text-slate-400'}`}>{speeds[key].label}<small className="mt-1 block font-medium text-slate-500">{speeds[key].detail}</small></button>)}</div></Config><Config title="Duración" icon={Timer}><div className="grid grid-cols-3 gap-2">{[60,120,180].map(value=><button key={value} disabled={running} onClick={()=>setDuration(value)} className={`h-14 rounded-xl border font-black disabled:opacity-40 ${duration===value?'border-cyan-300/35 bg-cyan-500/15 text-cyan-200':'border-white/10 bg-black/20 text-slate-400'}`}>{value/60} min</button>)}</div></Config><Config title="Repeticiones por combinación" icon={Repeat2}><div className="grid grid-cols-4 gap-2">{[2,3,4,5].map(value=><button key={value} disabled={running} onClick={()=>setReps(value)} className={`h-12 rounded-xl border font-black disabled:opacity-40 ${reps===value?'border-amber-300/35 bg-amber-500/15 text-amber-200':'border-white/10 bg-black/20 text-slate-400'}`}>{value}</button>)}</div></Config><Config title="Familias activas" icon={Dumbbell}><div className="space-y-2">{(["boxeo","patadas","defensa"] as Family[]).map(family=><button key={family} disabled={running} onClick={()=>setFamilies(value=>({...value,[family]:!value[family]}))} className={`flex min-h-11 w-full items-center justify-between rounded-xl border px-3 text-sm font-bold capitalize disabled:opacity-40 ${families[family]?'border-emerald-300/25 bg-emerald-500/10 text-white':'border-white/10 bg-black/20 text-slate-500'}`}>{family}{families[family]&&<Check className="h-4 w-4 text-emerald-300"/>}</button>)}</div></Config><div className="grid grid-cols-2 gap-2"><Option active={sound} onClick={()=>setSound(value=>!value)} icon={sound?AudioLines:VolumeX} label="Pitidos"/><Option active={voice} onClick={()=>setVoice(value=>!value)} icon={voice?Volume2:VolumeX} label="Voz"/></div><button onClick={()=>void start()} disabled={running||!enabled.length} className="flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-cyan-400 font-black text-cyan-950 disabled:opacity-40"><Play/>Iniciar ejercicio</button></aside>
  <div className="space-y-4"><PairBoard activeSide={activeSide} combo={current} rep={rep} reps={reps} running={running} paused={paused}/><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Tiempo" value={clock}/><Stat label="Repetición" value={`${rep}/${reps}`}/><Stat label="Serie" value={`${Math.min(series+1,2)}/2`}/><Stat label="Total" value={String(totalReps)}/></div><div className="flex flex-wrap justify-center gap-2"><button onClick={reset} className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/10 bg-white/[.05] px-4 font-bold"><RotateCcw className="h-4 w-4"/>Reiniciar</button><button onClick={pause} disabled={!running} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-amber-300 px-5 font-black text-amber-950 disabled:opacity-40">{paused?<Play/>:<Pause/>}{paused?"Continuar":"Pausar"}</button><button onClick={()=>{const combo=pickCombo();tones(2);speak(combo.name)}} disabled={!running||paused} className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/10 bg-white/[.05] px-4 font-bold disabled:opacity-40"><SkipForward className="h-4 w-4"/>Otra combinación</button></div></div></section>
 </div>{presentation&&<PairPresentation combo={current} activeSide={activeSide} clock={clock} progress={progress} countdown={countdown} running={running} paused={paused} rep={rep} reps={reps} total={totalReps} onStart={()=>void start()} onPause={pause} onReset={reset} onClose={()=>void closeScreen()}/>}</main>
}

function PairBoard({activeSide,combo,rep,reps,running,paused}:{activeSide:Side;combo:Combination|null;rep:number;reps:number;running:boolean;paused:boolean}){return <section className="grid min-h-[520px] overflow-hidden rounded-[2rem] border border-white/10 bg-[#0d0f14] md:grid-cols-2"><SidePanel side="A" active={activeSide==="A"} combo={combo}/><SidePanel side="B" active={activeSide==="B"} combo={combo}/><div className="col-span-full border-t border-white/10 p-4 text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-slate-500">{paused?"Ejercicio pausado":running?`Repetición ${rep} de ${reps}`:"Configura la sesión y presiona iniciar"}</p></div></section>}
function SidePanel({side,active,combo}:{side:Side;active:boolean;combo:Combination|null}){return <article className={`relative grid min-h-[450px] place-items-center overflow-hidden border-white/10 p-5 text-center transition duration-500 first:border-b md:first:border-b-0 md:first:border-r ${active?'bg-[radial-gradient(circle_at_center,rgba(34,211,238,.18),transparent_60%)]':'bg-black/20 opacity-65'}`}><span className={`absolute left-4 top-4 grid h-12 w-12 place-items-center rounded-2xl text-xl font-black ${active?'bg-cyan-400 text-cyan-950':'bg-white/10 text-slate-400'}`}>{side}</span>{combo?<div><p className={`text-xs font-black uppercase tracking-[.22em] ${active?'text-cyan-300':'text-slate-500'}`}>{active?"EJECUTA":"RECIBE Y DEFIENDE"}</p>{active?<><h2 className="mt-5 text-4xl font-black leading-tight sm:text-5xl">{combo.name}</h2><p className="mt-4 font-mono text-2xl font-black tracking-widest text-amber-300">{combo.numbers}</p><div className="mt-6 flex flex-wrap justify-center gap-2">{combo.steps.map(step=><span key={step} className="rounded-xl border border-cyan-300/20 bg-cyan-500/10 px-3 py-2 text-xs font-black text-cyan-100">{step}</span>)}</div></>:<><Shield className="mx-auto mt-6 h-20 w-20 text-slate-500"/><p className="mx-auto mt-5 max-w-xs text-lg font-bold leading-7 text-slate-300">{combo.response}</p></>}</div>:<div><UsersRound className="mx-auto h-20 w-20 text-white/10"/><p className="mt-4 font-black text-slate-500">Lado {side}</p></div>}</article>}
function PairPresentation({combo,activeSide,clock,progress,countdown,running,paused,rep,reps,total,onStart,onPause,onReset,onClose}:{combo:Combination|null;activeSide:Side;clock:string;progress:number;countdown:number;running:boolean;paused:boolean;rep:number;reps:number;total:number;onStart:()=>void;onPause:()=>void;onReset:()=>void;onClose:()=>void}){return <div className="fixed inset-0 z-[100] overflow-hidden bg-[#05070a] text-white"><div className="absolute inset-x-0 top-0 h-2 bg-white/10"><div className="h-full bg-cyan-400 transition-[width] duration-1000" style={{width:`${progress}%`}}/></div><header className="absolute inset-x-0 top-2 z-20 flex items-center justify-between p-4 sm:p-6"><div><p className="text-xs font-black uppercase tracking-[.22em] text-cyan-300">Puzzle · Parejas</p><p className="text-sm text-white/50">Tres pitidos = cambiar lados</p></div><div className="flex items-center gap-3"><b className="rounded-2xl border border-white/10 bg-white/[.06] px-5 py-2 font-mono text-3xl tabular-nums sm:text-5xl">{clock}</b><button onClick={onClose} className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/[.06]" aria-label="Cerrar"><Minimize2/></button></div></header><main className="grid h-full place-items-center px-3 pb-28 pt-24">{countdown>0?<b className="animate-pulse text-[10rem] font-black text-cyan-300 sm:text-[15rem]">{countdown}</b>:paused?<div className="text-center"><Pause className="mx-auto h-24 w-24 text-amber-300"/><h2 className="mt-4 text-6xl font-black">PAUSA</h2></div>:combo?<div className="grid w-full max-w-[1500px] gap-3 md:grid-cols-2"><PresentationSide side="A" active={activeSide==="A"} combo={combo}/><PresentationSide side="B" active={activeSide==="B"} combo={combo}/></div>:<div className="text-center"><UsersRound className="mx-auto h-28 w-28 text-cyan-300"/><h2 className="mt-5 text-5xl font-black sm:text-8xl">PREPAREN PAREJAS</h2></div>}</main><footer className="absolute inset-x-0 bottom-0 flex items-center justify-between border-t border-white/10 bg-black/55 p-4 backdrop-blur-xl sm:p-5"><div><b className="text-2xl">{rep}/{reps}</b><span className="ml-2 text-xs font-black uppercase text-white/50">repeticiones</span></div><div className="flex gap-2"><button onClick={onReset} className="grid h-12 w-12 place-items-center rounded-xl border border-white/10 bg-white/[.06]"><RotateCcw/></button>{running?<button onClick={onPause} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-amber-300 px-6 font-black text-amber-950">{paused?<Play/>:<Pause/>}{paused?"Continuar":"Pausar"}</button>:<button onClick={onStart} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-cyan-400 px-6 font-black text-cyan-950"><Play/>Iniciar</button>}</div><div><b className="text-2xl">{total}</b><span className="ml-2 text-xs font-black uppercase text-white/50">totales</span></div></footer></div>}
function PresentationSide({side,active,combo}:{side:Side;active:boolean;combo:Combination}){return <article className={`relative grid min-h-[60vh] place-items-center rounded-[2.5rem] border p-6 text-center transition duration-500 ${active?'border-cyan-300/35 bg-cyan-500/15 shadow-[0_0_70px_rgba(34,211,238,.12)]':'border-white/10 bg-white/[.025] opacity-55'}`}><span className={`absolute left-5 top-5 grid h-16 w-16 place-items-center rounded-2xl text-3xl font-black ${active?'bg-cyan-400 text-cyan-950':'bg-white/10'}`}>{side}</span>{active?<div><p className="text-xl font-black uppercase tracking-[.25em] text-cyan-300">EJECUTA</p><h2 className="mt-6 text-5xl font-black leading-tight sm:text-7xl xl:text-8xl">{combo.name}</h2><p className="mt-6 font-mono text-4xl font-black tracking-[.18em] text-amber-300 sm:text-6xl">{combo.numbers}</p></div>:<div><Shield className="mx-auto h-24 w-24 text-slate-500"/><p className="mt-6 text-2xl font-black uppercase text-white/50">RECIBE Y DEFIENDE</p><p className="mx-auto mt-4 max-w-md text-xl leading-8 text-slate-300">{combo.response}</p></div>}</article>}
function Config({title,icon:Icon,children}:{title:string;icon:typeof Timer;children:React.ReactNode}){return <fieldset><legend className="mb-2 flex items-center gap-2 text-sm font-black"><Icon className="h-4 w-4 text-cyan-300"/>{title}</legend>{children}</fieldset>}
function Option({active,onClick,icon:Icon,label}:{active:boolean;onClick:()=>void;icon:typeof AudioLines;label:string}){return <button onClick={onClick} className={`flex min-h-12 items-center justify-center gap-2 rounded-xl border text-sm font-black ${active?'border-emerald-300/25 bg-emerald-500/10 text-emerald-100':'border-white/10 bg-black/20 text-slate-500'}`}><Icon className="h-4 w-4"/>{label}</button>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-[#11141a] p-4 text-center"><span className="text-[9px] font-black uppercase tracking-wider text-slate-500">{label}</span><b className="mt-1 block font-mono text-2xl tabular-nums">{value}</b></div>}
