"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, CirclePlus, ClipboardList, RefreshCw, Save, ToggleLeft, Trash2, Users } from "lucide-react";

import { useAuth } from "@/firebase";

type QuestionType = "rating" | "choice" | "text";
type QuestionDraft = { label: string; type: QuestionType; optionsText: string; required: boolean };
type Survey = { id: string; title: string; description: string; site: string; active: boolean; questions: Array<{ id: string; label: string; type: QuestionType; options: string[]; required: boolean }>; responseCount: number; responses?: Array<{ id: string; answers: Record<string, string | number> }>; createdAt: string | null };
const EMPTY_QUESTION: QuestionDraft = { label: "", type: "rating", optionsText: "", required: true };

export default function CustomSurveysAdminPage() {
  const auth = useAuth(); const [site, setSite] = useState("MMA"); const [surveys, setSurveys] = useState<Survey[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ title: "", description: "" }); const [questions, setQuestions] = useState<QuestionDraft[]>([{ ...EMPTY_QUESTION }]);
  useEffect(() => setSite(window.localStorage.getItem("userSede") || "MMA"), []);
  const bearer = useCallback(async () => ({ Authorization: `Bearer ${await auth.currentUser?.getIdToken()}` }), [auth]);
  const load = useCallback(async () => { if (!auth.currentUser) return; setLoading(true); try { const response = await fetch(`/api/admin/encuestas-personalizadas?sede=${encodeURIComponent(site)}`, { headers: await bearer(), cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setSurveys(data.surveys || []); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cargar."); } finally { setLoading(false); } }, [auth.currentUser, bearer, site]);
  useEffect(() => { void load(); }, [load]);
  const totals = useMemo(() => ({ active: surveys.filter((survey) => survey.active).length, responses: surveys.reduce((sum, survey) => sum + survey.responseCount, 0) }), [surveys]);

  function updateQuestion(index: number, patch: Partial<QuestionDraft>) { setQuestions((current) => current.map((question, questionIndex) => questionIndex === index ? { ...question, ...patch } : question)); }
  async function action(body: Record<string, unknown>) { const response = await fetch("/api/admin/encuestas-personalizadas", { method: "POST", headers: { "Content-Type": "application/json", ...(await bearer()) }, body: JSON.stringify({ ...body, sede: site }) }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setSurveys((current) => current.some((survey) => survey.id === data.survey.id) ? current.map((survey) => survey.id === data.survey.id ? data.survey : survey) : [data.survey, ...current]); return data; }
  async function create() { setSaving(true); setMessage(""); try { const normalized = questions.map((question) => ({ label: question.label, type: question.type, required: question.required, options: question.type === "choice" ? question.optionsText.split("\n").map((option) => option.trim()).filter(Boolean) : [] })); await action({ action: "create", ...form, questions: normalized, active: true }); setForm({ title: "", description: "" }); setQuestions([{ ...EMPTY_QUESTION }]); setMessage("Encuesta publicada. Ya aparece en los iPad de esta sede."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo crear."); } finally { setSaving(false); } }
  async function toggle(survey: Survey) { try { await action({ action: "set-active", id: survey.id, active: !survey.active }); setMessage(survey.active ? "Encuesta cerrada." : "Encuesta publicada en el iPad."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo actualizar."); } }

  return <main className="min-h-screen bg-[#08090c] px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6">
    <header className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#201214] to-[#111318] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-red-300"><ClipboardList className="h-4 w-4" /> Comunidad · {site}</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Encuestas personalizadas</h1><p className="mt-2 text-sm text-white/60">Crea preguntas y publícalas directamente en el modo kiosco del iPad.</p></div><button type="button" onClick={() => void load()} className="flex h-11 items-center gap-2 rounded-xl border border-white/20 px-4 font-black"><RefreshCw className="h-4 w-4" /> Actualizar</button></div></header>
    <section className="grid gap-3 sm:grid-cols-3"><Stat icon={ToggleLeft} label="Publicadas" value={totals.active} /><Stat icon={Users} label="Respuestas" value={totals.responses} /><Stat icon={BarChart3} label="Creadas" value={surveys.length} /></section>
    <section className="grid gap-4 rounded-3xl border border-red-400/15 bg-[#17181d] p-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Título"><input className="survey-input" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} maxLength={100} placeholder="Ej. ¿Qué seminario te interesa?" /></Field><Field label="Descripción"><input className="survey-input" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} maxLength={300} placeholder="Texto breve opcional" /></Field></div>
      <div className="grid gap-3">{questions.map((question, index) => <article key={index} className="grid gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 md:grid-cols-[1fr_180px_auto]"><Field label={`Pregunta ${index + 1}`}><input className="survey-input" value={question.label} onChange={(event) => updateQuestion(index, { label: event.target.value })} maxLength={160} placeholder="Escribe la pregunta" /></Field><Field label="Tipo"><select className="survey-input" value={question.type} onChange={(event) => updateQuestion(index, { type: event.target.value as QuestionType })}><option value="rating">Calificación 1–5</option><option value="choice">Opción múltiple</option><option value="text">Respuesta abierta</option></select></Field><button type="button" aria-label="Eliminar pregunta" disabled={questions.length === 1} onClick={() => setQuestions((current) => current.filter((_, itemIndex) => itemIndex !== index))} className="mt-6 h-12 w-12 rounded-xl border border-white/10 text-red-300 disabled:opacity-25"><Trash2 className="mx-auto h-4 w-4" /></button>{question.type === "choice" && <Field label="Opciones (una por línea)"><textarea className="survey-input min-h-28 py-3 md:col-span-3" value={question.optionsText} onChange={(event) => updateQuestion(index, { optionsText: event.target.value })} placeholder={"Sí\nNo\nTal vez"} /></Field>}<label className="flex items-center gap-2 text-sm font-bold text-white/70 md:col-span-3"><input type="checkbox" checked={question.required} onChange={(event) => updateQuestion(index, { required: event.target.checked })} /> Pregunta obligatoria</label></article>)}</div>
      <div className="grid gap-3 sm:grid-cols-2"><button type="button" disabled={questions.length >= 12} onClick={() => setQuestions((current) => [...current, { ...EMPTY_QUESTION }])} className="h-12 rounded-xl border border-white/15 font-black"><CirclePlus className="mr-2 inline h-4 w-4" /> Agregar pregunta</button><button type="button" disabled={saving} onClick={() => void create()} className="h-12 rounded-xl bg-red-500 font-black"><Save className="mr-2 inline h-4 w-4" /> {saving ? "Publicando…" : "Crear y publicar"}</button></div>
    </section>
    {message && <p className="rounded-xl border border-red-300/20 bg-red-300/10 px-4 py-3 text-sm font-bold text-red-50">{message}</p>}
    {loading ? <p className="rounded-2xl bg-[#17181d] p-8 text-center font-bold text-white/70">Cargando encuestas…</p> : surveys.length === 0 ? <p className="rounded-2xl bg-[#17181d] p-8 text-center font-bold text-white/70">Todavía no has creado encuestas personalizadas.</p> : <section className="grid gap-4 lg:grid-cols-2">{surveys.map((survey) => <article key={survey.id} className="rounded-2xl border border-white/10 bg-[#17181d] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-red-300">{survey.questions.length} preguntas</p><h2 className="mt-1 text-xl font-black">{survey.title}</h2><p className="mt-1 text-sm text-white/55">{survey.description || "Sin descripción"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${survey.active ? "bg-emerald-400/15 text-emerald-200" : "bg-white/10 text-white/60"}`}>{survey.active ? "Publicada" : "Cerrada"}</span></div><div className="mt-4 flex items-center justify-between rounded-xl bg-black/20 p-3"><span className="text-sm text-white/60"><b className="text-xl text-white">{survey.responseCount}</b> respuestas</span><button type="button" onClick={() => void toggle(survey)} className={`rounded-lg px-4 py-2 text-sm font-black ${survey.active ? "border border-white/15" : "bg-red-500"}`}>{survey.active ? "Cerrar" : "Publicar"}</button></div>{survey.responses && survey.responses.length > 0 && <details className="mt-3 rounded-xl border border-white/10 bg-black/20 p-3"><summary className="cursor-pointer text-sm font-black">Ver respuestas recientes</summary><div className="mt-3 grid gap-3">{survey.responses.map((response, responseIndex) => <div key={response.id} className="rounded-lg bg-white/[.04] p-3"><b className="text-xs text-red-200">Respuesta {responseIndex + 1}</b>{survey.questions.map((question) => <p key={question.id} className="mt-2 text-xs text-white/55">{question.label}<strong className="block text-sm text-white">{String(response.answers[question.id] ?? "—")}</strong></p>)}</div>)}</div></details>}</article>)}</section>}
  </div><style jsx global>{`.survey-input{height:3rem;width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.15);background:#090a0d;padding:0 .75rem;color:#fff;outline:none}.survey-input:focus{border-color:#f87171}.survey-input::placeholder{color:rgba(255,255,255,.3)}`}</style></main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-bold">{label}{children}</label>; }
function Stat({ icon: Icon, label, value }: { icon: typeof ToggleLeft; label: string; value: number }) { return <article className="rounded-2xl border border-white/10 bg-[#17181d] p-4"><Icon className="h-5 w-5 text-red-300" /><p className="mt-2 text-3xl font-black">{value}</p><p className="text-xs font-black uppercase tracking-wide text-white/60">{label}</p></article>; }
