"use client";
import {Medal,ShieldCheck,Target,Trophy} from "lucide-react";
import type {FitnessScoreReport} from "@/lib/fitness-scoring";

const tone=(score?:number)=>score===undefined?"border-white/10 text-slate-400":score>=90?"border-fuchsia-300/30 text-fuchsia-200":score>=75?"border-cyan-300/30 text-cyan-200":score>=60?"border-emerald-300/30 text-emerald-200":score>=40?"border-amber-300/30 text-amber-200":"border-rose-300/30 text-rose-200";
export function FitnessScoreOverview({report,compact=false}:{report:FitnessScoreReport;compact?:boolean}){
  if(!report.completed)return <section className="rounded-3xl border border-dashed border-white/10 bg-black/15 p-5 text-center text-sm text-slate-500">Registra una prueba para calcular puntaje, objetivo y nivel.</section>;
  return <section className={`overflow-hidden rounded-3xl border border-violet-300/20 bg-[radial-gradient(circle_at_top_right,rgba(168,85,247,.16),transparent_42%),rgba(2,6,23,.72)] ${compact?"p-4":"p-5"}`}>
    <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-400/15 text-violet-200"><Trophy className="h-5 w-5"/></span><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-violet-300">Batería 60 s</p><h3 className="text-lg font-black text-white">Puntaje de rendimiento</h3></div></div><div className="text-right"><b className="text-4xl text-white">{report.overall}<small className="text-sm text-slate-500">/100</small></b><span className="ml-3 rounded-full bg-white/[.07] px-3 py-1 text-[10px] font-black uppercase text-slate-300">{report.overallLabel}</span></div></div>
    <div className={`mt-4 grid gap-3 ${compact?"sm:grid-cols-2 xl:grid-cols-4":"md:grid-cols-2 xl:grid-cols-4"}`}>{report.exercises.map(item=><article key={item.key} className={`rounded-2xl border bg-black/20 p-4 ${tone(item.score)}`}><div className="flex items-start justify-between gap-3"><div><b className="text-sm text-white">{item.label}</b><p className="text-[10px] uppercase text-slate-500">{item.levelLabel}</p></div><b className="text-2xl">{item.score}</b></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span className="rounded-xl bg-white/[.04] p-2"><small className="block text-slate-500">Resultado</small><b className="text-white">{item.repetitions} reps</b></span><span className="rounded-xl bg-white/[.04] p-2"><small className="block text-slate-500">Referencia</small><b className="text-white">{item.target} reps</b></span></div>{item.change!==undefined&&<p className={`mt-2 text-[10px] font-bold ${item.change>=0?"text-emerald-300":"text-amber-200"}`}>{item.change>=0?"+":""}{item.change} frente al registro previo</p>}<p className="mt-2 line-clamp-2 text-[10px] leading-4 text-slate-500">{item.referenceLabel}</p></article>)}</div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-white/[.07] pt-4 text-xs"><p className="flex items-center gap-2 text-slate-400"><Target className="h-4 w-4 text-cyan-300"/>Promedio personal de {report.completed}/4 pruebas; las vacías no descuentan puntos.</p><p className="flex items-center gap-2 text-slate-500"><ShieldCheck className="h-4 w-4"/>{report.rankingEligible?"Batería completa: elegible para ranking":"El ranking se activa al completar las cuatro pruebas"}</p></div>
    <p className="mt-3 rounded-xl bg-white/[.035] p-3 text-[10px] leading-4 text-slate-500">Lagartijas y abdominales usan una referencia operativa de selección policial adulta únicamente cuando edad, sexo y protocolo de 60 segundos coinciden. No es un baremo universal de salud. Sentadillas y burpees priorizan evolución personal o pares comparables. El peso solo ayuda a formar pares: no suma ni resta puntos.</p>
  </section>;
}

export function FitnessRankBadge({rank,score}:{rank?:number;score?:number}){return <span className="inline-flex items-center gap-2 rounded-full border border-amber-300/20 bg-amber-400/10 px-3 py-1.5 text-xs font-black text-amber-200"><Medal className="h-4 w-4"/>{rank?`#${rank}`:"Sin rango"} · {score??"—"}/100</span>}
