"use client";
import { Activity, Dumbbell, Ruler, TrendingDown, TrendingUp } from "lucide-react";
import { bmiLevel,bodyFatLevel,waistHeightLevel,wellnessScore,type IndicatorLevel,type PhysicalAssessment } from "@/lib/athlete-progress";

const value = (number?: number, suffix = "") => number === undefined ? "—" : `${number}${suffix}`;
const delta = (current?: number, previous?: number) => current === undefined || previous === undefined ? null : Math.round((current - previous) * 10) / 10;

export function PhysicalHistory({ records }: { records: PhysicalAssessment[] }) {
  if (!records.length) return <div className="rounded-3xl border border-dashed border-white/15 p-12 text-center"><Activity className="mx-auto h-9 w-9 text-slate-500"/><p className="mt-3 font-black text-white">Sin evaluaciones todavía</p><p className="text-sm text-slate-400">La primera medición establecerá la línea base.</p></div>;
  const latest=records[0], previous=records[1];
  const score=wellnessScore({bmi:latest.imc,waistHeight:latest.cinturaEstatura,bodyFat:latest.grasaPorcentaje,sex:latest.sexoCalculo});
  return <div className="space-y-6">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Peso actual" current={latest.pesoKg} previous={previous?.pesoKg} suffix=" kg"/><Summary label="IMC calculado" current={latest.imc} previous={previous?.imc}/><Summary label="Grasa medida" current={latest.grasaPorcentaje} previous={previous?.grasaPorcentaje} suffix="%"/><Summary label="Cintura" current={latest.cinturaCm} previous={previous?.cinturaCm} suffix=" cm"/></div>
    <section className="grid gap-6 rounded-3xl border border-white/10 bg-slate-900/70 p-5 lg:grid-cols-[1fr_260px]"><div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-cyan-300">Balance de indicadores</p><h2 className="text-2xl font-black text-white">{score===undefined?'Datos insuficientes':`${score} de 100`}</h2></div><span className="text-xs text-slate-400">Orientativo · no diagnóstico</span></div><div className="mt-6 space-y-5"><Indicator label="IMC" value={latest.imc} max={40} level={bmiLevel(latest.imc)}/><Indicator label="Cintura / estatura" value={latest.cinturaEstatura} max={0.75} level={waistHeightLevel(latest.cinturaEstatura)}/><Indicator label={latest.grasaAutomatica?'PGC estimado':'PGC medido'} value={latest.grasaPorcentaje} max={50} level={bodyFatLevel(latest.grasaPorcentaje,latest.sexoCalculo)}/></div><div className="mt-5 flex flex-wrap gap-4 text-xs text-slate-400"><Key level="green" text="Zona favorable"/><Key level="yellow" text="Revisar"/><Key level="red" text="Atención"/><Key level="neutral" text="Sin datos"/></div></div><BodySilhouette bmi={bmiLevel(latest.imc)} waist={waistHeightLevel(latest.cinturaEstatura)} fat={bodyFatLevel(latest.grasaPorcentaje,latest.sexoCalculo)}/></section>
    {records.map((record,index)=><article key={record.id} className="overflow-hidden rounded-3xl border border-white/10 bg-slate-900/70"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 bg-white/[.03] px-5 py-4"><div><p className="font-black text-white">{new Date(`${record.fecha}T12:00:00`).toLocaleDateString("es-MX",{dateStyle:"long"})}</p><p className="text-xs text-slate-400">{index===0?"Evaluación más reciente":`Evaluación anterior ${index}`}</p></div><span className="rounded-xl bg-cyan-500/15 px-3 py-2 text-sm font-black text-cyan-100">IMC {record.imc}</span></header><div className="grid gap-0 lg:grid-cols-2"><section className="p-5 lg:border-r lg:border-white/10"><Heading icon={Ruler} title="Composición y medidas"/><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric label="Peso" value={value(record.pesoKg," kg")}/><Metric label="Estatura" value={value(record.estaturaCm," cm")}/><Metric label="Grasa corporal" value={value(record.grasaPorcentaje,"%")}/><Metric label="Cintura" value={value(record.cinturaCm," cm")}/><Metric label="Cadera" value={value(record.caderaCm," cm")}/><Metric label="Pecho" value={value(record.pechoCm," cm")}/><Metric label="Brazo" value={value(record.brazoCm," cm")}/><Metric label="Muslo" value={value(record.musloCm," cm")}/><Metric label="Cintura/estatura" value={value(record.cinturaEstatura)}/><Metric label="Cintura/cadera" value={value(record.cinturaCadera)}/></div>{record.metodoGrasa&&<p className="mt-3 text-xs text-slate-400">Método de grasa: {record.metodoGrasa}</p>}</section><section className="border-t border-white/10 p-5 lg:border-t-0"><Heading icon={Dumbbell} title="Pruebas físicas"/><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric label="Lagartijas" value={value(record.lagartijas," reps")}/><Metric label="Sentadillas" value={value(record.sentadillas," reps")}/><Metric label="Abdominales" value={value(record.abdominales," reps")}/><Metric label="Navette nivel" value={value(record.navetteNivel)}/><Metric label="Navette idas" value={value(record.navetteIdas)}/></div></section></div>{record.notas&&<p className="border-t border-white/10 px-5 py-4 text-sm text-slate-300">{record.notas}</p>}</article>)}
    <p className="text-xs text-slate-500">El IMC y los cocientes se calculan automáticamente como referencias de seguimiento; no sustituyen una valoración médica ni distinguen masa muscular de grasa.</p>
  </div>;
}
function Heading({icon:Icon,title}:{icon:typeof Ruler;title:string}){return <div className="mb-4 flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-500/15 text-cyan-300"><Icon className="h-4 w-4"/></span><h3 className="font-black text-white">{title}</h3></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-black/20 p-3"><span className="block text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</span><b className="mt-1 block text-sm text-white">{value}</b></div>}
function Summary({label,current,previous,suffix=""}:{label:string;current?:number;previous?:number;suffix?:string}){const change=delta(current,previous);return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</span><div className="mt-1 flex items-end justify-between gap-2"><b className="text-2xl text-white">{value(current,suffix)}</b>{change!==null&&change!==0&&<span className={`flex items-center text-xs font-bold ${change>0?'text-amber-300':'text-emerald-300'}`}>{change>0?<TrendingUp className="h-3 w-3"/>:<TrendingDown className="h-3 w-3"/>}{change>0?'+':''}{change}</span>}</div></div>}
const levelColor:Record<IndicatorLevel,string>={green:"bg-emerald-400",yellow:"bg-amber-400",red:"bg-red-400",neutral:"bg-slate-600"};
const svgColor:Record<IndicatorLevel,string>={green:"#34d399",yellow:"#fbbf24",red:"#f87171",neutral:"#475569"};
function Indicator({label,value,max,level}:{label:string;value?:number;max:number;level:IndicatorLevel}){const width=value===undefined?0:Math.min(100,value/max*100);return <div><div className="mb-1.5 flex justify-between text-sm"><b className="text-slate-200">{label}</b><span className="text-white">{value??'—'}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full ${levelColor[level]}`} style={{width:`${width}%`}}/></div></div>}
function Key({level,text}:{level:IndicatorLevel;text:string}){return <span className="flex items-center gap-1.5"><i className={`h-2.5 w-2.5 rounded-full ${levelColor[level]}`}/>{text}</span>}
function BodySilhouette({bmi,waist,fat}:{bmi:IndicatorLevel;waist:IndicatorLevel;fat:IndicatorLevel}){return <figure className="grid place-items-center"><svg viewBox="0 0 180 300" className="h-72 max-w-full" role="img" aria-label="Silueta corporal coloreada por indicadores"><title>Mapa corporal orientativo: cuerpo general por PGC, torso por IMC y abdomen por cintura-estatura</title><circle cx="90" cy="30" r="22" fill={svgColor[fat]} opacity=".9"/><path d="M65 58 Q90 48 115 58 L130 135 Q119 151 108 158 L116 275 Q105 286 94 275 L90 177 L86 275 Q75 286 64 275 L72 158 Q61 151 50 135Z" fill={svgColor[fat]} opacity=".82"/><path d="M67 60 Q90 51 113 60 L121 130 Q90 145 59 130Z" fill={svgColor[bmi]} opacity=".95"/><ellipse cx="90" cy="128" rx="32" ry="25" fill={svgColor[waist]} opacity=".95"/><path d="M58 69 L29 155 Q23 160 17 151 L45 60Z M122 69 L151 155 Q157 160 163 151 L135 60Z" fill={svgColor[fat]} opacity=".82"/></svg><figcaption className="text-center text-xs text-slate-400">Cabeza y extremidades: PGC · torso: IMC · abdomen: cintura/estatura</figcaption></figure>}
