"use client";
import { Activity, Dumbbell, Ruler, TrendingDown, TrendingUp } from "lucide-react";
import type { PhysicalAssessment } from "@/lib/athlete-progress";

const value = (number?: number, suffix = "") => number === undefined ? "—" : `${number}${suffix}`;
const delta = (current?: number, previous?: number) => current === undefined || previous === undefined ? null : Math.round((current - previous) * 10) / 10;

export function PhysicalHistory({ records }: { records: PhysicalAssessment[] }) {
  if (!records.length) return <div className="rounded-3xl border border-dashed border-white/15 p-12 text-center"><Activity className="mx-auto h-9 w-9 text-slate-500"/><p className="mt-3 font-black text-white">Sin evaluaciones todavía</p><p className="text-sm text-slate-400">La primera medición establecerá la línea base.</p></div>;
  const latest=records[0], previous=records[1];
  return <div className="space-y-6">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Peso actual" current={latest.pesoKg} previous={previous?.pesoKg} suffix=" kg"/><Summary label="IMC calculado" current={latest.imc} previous={previous?.imc}/><Summary label="Grasa medida" current={latest.grasaPorcentaje} previous={previous?.grasaPorcentaje} suffix="%"/><Summary label="Cintura" current={latest.cinturaCm} previous={previous?.cinturaCm} suffix=" cm"/></div>
    {records.map((record,index)=><article key={record.id} className="overflow-hidden rounded-3xl border border-white/10 bg-slate-900/70"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 bg-white/[.03] px-5 py-4"><div><p className="font-black text-white">{new Date(`${record.fecha}T12:00:00`).toLocaleDateString("es-MX",{dateStyle:"long"})}</p><p className="text-xs text-slate-400">{index===0?"Evaluación más reciente":`Evaluación anterior ${index}`}</p></div><span className="rounded-xl bg-cyan-500/15 px-3 py-2 text-sm font-black text-cyan-100">IMC {record.imc}</span></header><div className="grid gap-0 lg:grid-cols-2"><section className="p-5 lg:border-r lg:border-white/10"><Heading icon={Ruler} title="Composición y medidas"/><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric label="Peso" value={value(record.pesoKg," kg")}/><Metric label="Estatura" value={value(record.estaturaCm," cm")}/><Metric label="Grasa corporal" value={value(record.grasaPorcentaje,"%")}/><Metric label="Cintura" value={value(record.cinturaCm," cm")}/><Metric label="Cadera" value={value(record.caderaCm," cm")}/><Metric label="Pecho" value={value(record.pechoCm," cm")}/><Metric label="Brazo" value={value(record.brazoCm," cm")}/><Metric label="Muslo" value={value(record.musloCm," cm")}/><Metric label="Cintura/estatura" value={value(record.cinturaEstatura)}/><Metric label="Cintura/cadera" value={value(record.cinturaCadera)}/></div>{record.metodoGrasa&&<p className="mt-3 text-xs text-slate-400">Método de grasa: {record.metodoGrasa}</p>}</section><section className="border-t border-white/10 p-5 lg:border-t-0"><Heading icon={Dumbbell} title="Pruebas físicas"/><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric label="Lagartijas" value={value(record.lagartijas," reps")}/><Metric label="Sentadillas" value={value(record.sentadillas," reps")}/><Metric label="Abdominales" value={value(record.abdominales," reps")}/><Metric label="Navette nivel" value={value(record.navetteNivel)}/><Metric label="Navette idas" value={value(record.navetteIdas)}/></div></section></div>{record.notas&&<p className="border-t border-white/10 px-5 py-4 text-sm text-slate-300">{record.notas}</p>}</article>)}
    <p className="text-xs text-slate-500">El IMC y los cocientes se calculan automáticamente como referencias de seguimiento; no sustituyen una valoración médica ni distinguen masa muscular de grasa.</p>
  </div>;
}
function Heading({icon:Icon,title}:{icon:typeof Ruler;title:string}){return <div className="mb-4 flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-500/15 text-cyan-300"><Icon className="h-4 w-4"/></span><h3 className="font-black text-white">{title}</h3></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-black/20 p-3"><span className="block text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</span><b className="mt-1 block text-sm text-white">{value}</b></div>}
function Summary({label,current,previous,suffix=""}:{label:string;current?:number;previous?:number;suffix?:string}){const change=delta(current,previous);return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</span><div className="mt-1 flex items-end justify-between gap-2"><b className="text-2xl text-white">{value(current,suffix)}</b>{change!==null&&change!==0&&<span className={`flex items-center text-xs font-bold ${change>0?'text-amber-300':'text-emerald-300'}`}>{change>0?<TrendingUp className="h-3 w-3"/>:<TrendingDown className="h-3 w-3"/>}{change>0?'+':''}{change}</span>}</div></div>}
