"use client";
/* eslint-disable @typescript-eslint/no-unused-vars -- reserved PGC input keeps the activity-ring API extensible */
import type React from "react";
import { Activity,ArrowDownRight,ArrowUpRight,ChevronRight,Dumbbell,HeartPulse,Ruler,Sparkles,TrendingUp } from "lucide-react";
import { bmiLevel,bodyFatLevel,waistHeightLevel,wellnessScore,type IndicatorLevel,type PhysicalAssessment } from "@/lib/athlete-progress";

const show=(number?:number,suffix="")=>number===undefined?"—":`${number}${suffix}`;
const difference=(current?:number,previous?:number)=>current===undefined||previous===undefined?null:Math.round((current-previous)*10)/10;
const tone:Record<IndicatorLevel,{hex:string,text:string,bg:string,label:string}>={green:{hex:"#32d583",text:"text-emerald-300",bg:"bg-emerald-400",label:"Óptimo"},yellow:{hex:"#fbbf24",text:"text-amber-300",bg:"bg-amber-400",label:"Atención"},red:{hex:"#fb7185",text:"text-rose-300",bg:"bg-rose-400",label:"Revisar"},neutral:{hex:"#475569",text:"text-slate-500",bg:"bg-slate-600",label:"Sin datos"}};

export function PhysicalHistory({records}:{records:PhysicalAssessment[]}){
 if(!records.length)return <div className="rounded-[2rem] border border-white/10 bg-white/[.035] p-14 text-center shadow-2xl"><Activity className="mx-auto h-10 w-10 text-cyan-300"/><p className="mt-4 text-xl font-black text-white">Comienza tu línea base</p><p className="mt-1 text-sm text-slate-400">Guarda la primera evaluación para activar tendencias y mapa corporal.</p></div>;
 const latest=records[0],previous=records[1],bmi=bmiLevel(latest.imc),waist=waistHeightLevel(latest.cinturaEstatura),fat=bodyFatLevel(latest.grasaPorcentaje,latest.sexoCalculo),score=wellnessScore({bmi:latest.imc,waistHeight:latest.cinturaEstatura,bodyFat:latest.grasaPorcentaje,sex:latest.sexoCalculo});
 return <div className="relative isolate space-y-6 before:pointer-events-none before:absolute before:-inset-8 before:-z-10 before:bg-[radial-gradient(circle_at_15%_10%,rgba(168,85,247,.12),transparent_24%),radial-gradient(circle_at_88%_24%,rgba(34,211,238,.12),transparent_25%),radial-gradient(circle_at_50%_80%,rgba(244,63,94,.08),transparent_30%)]">
  <section className="relative overflow-hidden rounded-[2.25rem] border border-white/10 bg-[radial-gradient(circle_at_top_right,_rgba(34,211,238,.16),_transparent_35%),linear-gradient(135deg,rgba(15,23,42,.98),rgba(2,6,23,.98))] p-5 shadow-[0_30px_80px_rgba(0,0,0,.35)] md:p-8"><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl"/><header className="relative flex flex-wrap items-end justify-between gap-5"><div><div className="mb-2 flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-cyan-300"><Sparkles className="h-4 w-4"/> Health Intelligence</div><h2 className="text-3xl font-black tracking-tight text-white">Tu estado, de un vistazo</h2><p className="mt-1 text-sm text-slate-400">Última evaluación · {formatDate(latest.fecha)}</p></div><div className="flex items-center gap-4"><div className="relative grid h-28 w-28 place-items-center rounded-full p-2" style={{background:`conic-gradient(${scoreColor(score)} ${(score||0)*3.6}deg,rgba(255,255,255,.08) 0)`}}><div className="grid h-full w-full place-items-center rounded-full bg-slate-950/95"><div className="text-center"><b className="block text-3xl text-white">{score??'—'}</b><span className="text-[10px] font-black uppercase tracking-wide text-slate-500">Balance</span></div></div></div></div></header>
   <div className="relative mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><HeroMetric label="Peso" value={latest.pesoKg} previous={previous?.pesoKg} suffix=" kg"/><HeroMetric label="IMC" value={latest.imc} previous={previous?.imc} level={bmi}/><HeroMetric label={latest.grasaAutomatica?"PGC estimado":"Grasa corporal"} value={latest.grasaPorcentaje} previous={previous?.grasaPorcentaje} suffix="%" level={fat}/><HeroMetric label="Cintura" value={latest.cinturaCm} previous={previous?.cinturaCm} suffix=" cm" level={waist}/></div>
  </section>

  <section className="relative overflow-hidden rounded-[2rem] border border-white/[.14] bg-white/[.07] p-5 shadow-[0_28px_80px_rgba(0,0,0,.45),inset_0_1px_rgba(255,255,255,.16)] backdrop-blur-2xl md:p-7"><div className="pointer-events-none absolute inset-x-12 top-0 h-px bg-gradient-to-r from-transparent via-white/60 to-transparent"/><div className="grid items-center gap-7 lg:grid-cols-[260px_1fr]"><WellnessRings score={score} bmi={latest.imc} fat={latest.grasaPorcentaje} waist={latest.cinturaEstatura}/><div><p className="text-xs font-black uppercase tracking-[.22em] text-slate-500">Círculos de bienestar</p><h3 className="mt-1 text-2xl font-black tracking-tight text-white">Tres métricas. Una visión completa.</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><RingLabel color="bg-rose-400" label="Balance" value={`${score??'—'}/100`}/><RingLabel color="bg-lime-400" label="IMC" value={show(latest.imc)}/><RingLabel color="bg-cyan-400" label="Cintura/altura" value={show(latest.cinturaEstatura)}/></div></div></div></section>

  <div className="grid gap-6 xl:grid-cols-[1.08fr_.92fr]">
   <section className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.035] shadow-[0_20px_60px_rgba(0,0,0,.25)]"><header className="flex items-center justify-between border-b border-white/[.07] p-5 md:px-6"><div><p className="text-xs font-black uppercase tracking-[.2em] text-slate-500">Mapa corporal</p><h3 className="mt-1 text-xl font-black text-white">Zonas de equilibrio</h3></div><HeartPulse className="h-6 w-6 text-rose-300"/></header><div className="grid items-center gap-5 p-5 sm:grid-cols-[1fr_190px] md:p-6"><BodyMap sex={latest.sexoCalculo} bmi={bmi} waist={waist} fat={fat}/><div className="space-y-3"><ZoneRow color={fat} label="Composición general" value={show(latest.grasaPorcentaje,'%')}/><ZoneRow color={bmi} label="Torso · IMC" value={show(latest.imc)}/><ZoneRow color={waist} label="Zona abdominal" value={show(latest.cinturaEstatura)}/><p className="pt-2 text-[11px] leading-relaxed text-slate-500">Los colores representan indicadores de seguimiento, no lesiones ni diagnósticos por región.</p></div></div></section>
   <section className="rounded-[2rem] border border-white/10 bg-white/[.035] p-5 shadow-[0_20px_60px_rgba(0,0,0,.25)] md:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-slate-500">Evolución</p><h3 className="mt-1 text-xl font-black text-white">Tendencia corporal</h3></div><TrendingUp className="h-6 w-6 text-cyan-300"/></div><TrendChart records={records}/><div className="mt-5 grid grid-cols-3 gap-2"><SmallStat label="Cintura/altura" value={show(latest.cinturaEstatura)}/><SmallStat label="Cintura/cadera" value={show(latest.cinturaCadera)}/><SmallStat label="Evaluaciones" value={String(records.length)}/></div></section>
  </div>

  <section className="grid gap-4 md:grid-cols-2"><DataPanel icon={Ruler} title="Composición y medidas"><MetricGrid items={[["Estatura",show(latest.estaturaCm," cm")],["Cadera",show(latest.caderaCm," cm")],["Pecho",show(latest.pechoCm," cm")],["Brazo",show(latest.brazoCm," cm")],["Muslo",show(latest.musloCm," cm")],["Método PGC",latest.metodoGrasa||"—"]]}/></DataPanel><DataPanel icon={Dumbbell} title="Rendimiento físico"><MetricGrid items={[["Lagartijas",show(latest.lagartijas," reps")],["Sentadillas",show(latest.sentadillas," reps")],["Abdominales",show(latest.abdominales," reps")],["Navette",latest.navetteNivel?`Nivel ${latest.navetteNivel}`:"—"],["Vueltas",show(latest.navetteIdas)],["Distancia",latest.navetteIdas?`${latest.navetteIdas*20} m`:"—"]]}/></DataPanel></section>

  {records.length>1&&<section className="rounded-[2rem] border border-white/10 bg-white/[.025] p-5 md:p-6"><h3 className="font-black text-white">Historial de evaluaciones</h3><div className="mt-4 divide-y divide-white/[.07]">{records.slice(1).map(record=><div key={record.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><b className="text-sm text-white">{formatDate(record.fecha)}</b><p className="text-xs text-slate-500">IMC {record.imc} · PGC {show(record.grasaPorcentaje,'%')}</p></div><div className="flex items-center gap-4 text-sm text-slate-300"><span>{record.pesoKg} kg</span><span>{show(record.cinturaCm,' cm')}</span><ChevronRight className="h-4 w-4 text-slate-600"/></div></div>)}</div></section>}
  <p className="px-2 text-xs leading-relaxed text-slate-600">Panel orientativo de seguimiento. Las estimaciones y colores no sustituyen evaluación médica ni medición clínica de composición corporal.</p>
 </div>;
}

function HeroMetric({label,value,previous,suffix="",level="neutral"}:{label:string;value?:number;previous?:number;suffix?:string;level?:IndicatorLevel}){const change=difference(value,previous);return <div className="rounded-2xl border border-white/[.08] bg-white/[.055] p-4 backdrop-blur"><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-400">{label}</span>{level!=="neutral"&&<i className={`h-2.5 w-2.5 rounded-full ${tone[level].bg} shadow-[0_0_10px_currentColor]`}/>}</div><b className="mt-2 block text-2xl tracking-tight text-white">{show(value,suffix)}</b>{change!==null&&change!==0?<span className={`mt-1 flex items-center text-xs font-bold ${change>0?'text-amber-300':'text-emerald-300'}`}>{change>0?<ArrowUpRight className="h-3 w-3"/>:<ArrowDownRight className="h-3 w-3"/>}{change>0?'+':''}{change}{suffix} vs. anterior</span>:<span className="mt-1 block text-xs text-slate-600">Sin cambio registrado</span>}</div>}
function BodyMap({sex,bmi,waist,fat}:{sex?:"masculino"|"femenino";bmi:IndicatorLevel;waist:IndicatorLevel;fat:IndicatorLevel}){const female=sex==="femenino",positions=female?["66.66%","100%"]:["0%","33.33%"];const gradient=`linear-gradient(to bottom,${tone[fat].hex} 0 27%,${tone[bmi].hex} 27% 50%,${tone[waist].hex} 50% 65%,${tone[fat].hex} 65% 100%)`;return <figure><div className="flex h-80 items-end justify-center gap-1">{positions.map((position,index)=><div key={position} className="h-full w-1/2" style={{background:gradient,WebkitMaskImage:"url('/cuerpo.png')",maskImage:"url('/cuerpo.png')",WebkitMaskRepeat:"no-repeat",maskRepeat:"no-repeat",WebkitMaskSize:"400% 100%",maskSize:"400% 100%",WebkitMaskPosition:`${position} center`,maskPosition:`${position} center`,filter:"drop-shadow(0 12px 20px rgba(0,0,0,.45))"}} aria-label={`Vista ${index===0?'frontal':'posterior'} de la silueta`}/>)}</div><figcaption className="mt-2 text-center text-xs font-bold text-slate-500">{female?'Silueta femenina':'Silueta masculina'} · frontal y posterior</figcaption></figure>}
function ZoneRow({color,label,value}:{color:IndicatorLevel;label:string;value:string}){return <div className="flex items-center gap-3 rounded-2xl bg-black/20 p-3"><i className={`h-10 w-1 rounded-full ${tone[color].bg}`}/><div className="min-w-0 flex-1"><span className="block truncate text-xs text-slate-400">{label}</span><b className="text-sm text-white">{value}</b></div><span className={`text-[10px] font-black uppercase ${tone[color].text}`}>{tone[color].label}</span></div>}
function TrendChart({records}:{records:PhysicalAssessment[]}){const data=[...records].reverse().slice(-8),weights=data.map(item=>item.pesoKg),min=Math.min(...weights),max=Math.max(...weights),range=Math.max(1,max-min),points=data.map((item,index)=>`${data.length===1?50:index/(data.length-1)*100},${74-(item.pesoKg-min)/range*52}`).join(' ');return <div className="mt-6"><svg viewBox="0 0 100 86" className="h-52 w-full overflow-visible" role="img" aria-label="Gráfica del peso a través del tiempo"><defs><linearGradient id="healthArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#22d3ee" stopOpacity=".35"/><stop offset="1" stopColor="#22d3ee" stopOpacity="0"/></linearGradient></defs><path d={`M ${points} L 100 82 L 0 82 Z`} fill="url(#healthArea)"/><polyline points={points} fill="none" stroke="#22d3ee" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>{data.map((item,index)=>{const x=data.length===1?50:index/(data.length-1)*100,y=74-(item.pesoKg-min)/range*52;return <g key={item.id}><circle cx={x} cy={y} r="2.8" fill="#020617" stroke="#67e8f9" strokeWidth="1.5"/><text x={x} y={y-6} textAnchor="middle" fill="#cbd5e1" fontSize="5">{item.pesoKg}</text></g>})}</svg><div className="flex justify-between text-[10px] font-bold uppercase text-slate-600"><span>{formatDate(data[0]?.fecha,true)}</span><span>Peso (kg)</span><span>{formatDate(data.at(-1)?.fecha,true)}</span></div></div>}
function SmallStat({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-black/20 p-3"><span className="block text-[10px] font-bold uppercase text-slate-500">{label}</span><b className="mt-1 block text-sm text-white">{value}</b></div>}
function DataPanel({icon:Icon,title,children}:{icon:typeof Ruler;title:string;children:React.ReactNode}){return <section className="rounded-[2rem] border border-white/10 bg-white/[.035] p-5 md:p-6"><header className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-500/10 text-cyan-300"><Icon className="h-5 w-5"/></span><h3 className="font-black text-white">{title}</h3></header>{children}</section>}
function MetricGrid({items}:{items:[string,string][]}){return <div className="grid grid-cols-2 gap-x-5 gap-y-4 sm:grid-cols-3">{items.map(([label,value])=><div key={label} className="border-b border-white/[.07] pb-3"><span className="block text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</span><b className="mt-1 block truncate text-sm text-slate-100">{value}</b></div>)}</div>}
function scoreColor(score?:number){return score===undefined?'#475569':score>=80?'#32d583':score>=55?'#fbbf24':'#fb7185'}
function formatDate(date?:string,short=false){if(!date)return'—';return new Date(`${date}T12:00:00`).toLocaleDateString('es-MX',short?{month:'short',year:'2-digit'}:{day:'numeric',month:'long',year:'numeric'})}
function WellnessRings({score,bmi,fat,waist}:{score?:number;bmi?:number;fat?:number;waist?:number}){const first=score||0,second=bmi?Math.min(100,bmi/35*100):0,third=waist?Math.min(100,waist/.65*100):0;return <div className="relative mx-auto grid h-56 w-56 place-items-center"><div className="absolute inset-0 rounded-full p-[13px]" style={{background:`conic-gradient(#fb2c6d ${first*3.6}deg,rgba(255,255,255,.07) 0)`}}><div className="h-full w-full rounded-full bg-[#090b10]"/></div><div className="absolute inset-[24px] rounded-full p-[13px]" style={{background:`conic-gradient(#9cff00 ${second*3.6}deg,rgba(255,255,255,.07) 0)`}}><div className="h-full w-full rounded-full bg-[#090b10]"/></div><div className="absolute inset-[48px] rounded-full p-[13px]" style={{background:`conic-gradient(#00e5ef ${third*3.6}deg,rgba(255,255,255,.07) 0)`}}><div className="h-full w-full rounded-full bg-[#090b10]"/></div><div className="relative text-center"><b className="block text-3xl text-white">{score??'—'}</b><span className="text-[10px] font-black uppercase tracking-[.2em] text-slate-500">Score</span></div></div>}
function RingLabel({color,label,value}:{color:string;label:string;value:string}){return <div className="rounded-2xl border border-white/[.08] bg-black/20 p-3 shadow-inner"><div className="flex items-center gap-2"><i className={`h-2.5 w-2.5 rounded-full ${color} shadow-[0_0_10px_currentColor]`}/><span className="text-xs font-bold text-slate-400">{label}</span></div><b className="mt-2 block text-xl text-white">{value}</b></div>}
