"use client";

import type React from "react";
import { Check, Crown, Flame, LockKeyhole, Shield, Sparkles, Star, Swords, Zap } from "lucide-react";
import { SKILL_TREES, nextSkillStatus, type SkillDiscipline, type SkillProgress } from "@/lib/athlete-progress";
import { cn } from "@/lib/utils";

const branchIcons=[Shield,Swords,Zap,Flame];

export function SkillTreeView({ discipline, progress, editable = false, saving = false, onChange }: { discipline: SkillDiscipline; progress: SkillProgress; editable?: boolean; saving?: boolean; onChange?: (next: SkillProgress) => void }) {
  const branches=SKILL_TREES[discipline];
  const allSkills=branches.flatMap(([,skills])=>[...skills]);
  const mastered=allSkills.filter(skill=>progress[skill]==="dominada").length;
  const training=allSkills.filter(skill=>progress[skill]==="practicando").length;
  const percent=Math.round(mastered/allSkills.length*100);
  const rank=percent===100?"Maestro de la disciplina":percent>=75?"Élite":percent>=50?"Guerrero avanzado":percent>=25?"Combatiente":"Iniciado";

  return <div className="relative overflow-hidden rounded-[2rem] border border-amber-500/30 bg-[#07090f] text-white shadow-[0_30px_100px_rgba(0,0,0,.65),inset_0_0_80px_rgba(245,158,11,.04)]">
    <div className="pointer-events-none absolute inset-0 opacity-50" style={{backgroundImage:"radial-gradient(circle at 50% 0%,rgba(245,158,11,.18),transparent 30%),radial-gradient(circle at 10% 45%,rgba(59,130,246,.12),transparent 24%),radial-gradient(circle at 90% 55%,rgba(139,92,246,.12),transparent 25%),linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px)",backgroundSize:"auto,auto,auto,32px 32px,32px 32px"}}/>
    <header className="relative border-b border-amber-500/20 bg-gradient-to-b from-amber-500/10 to-transparent px-5 py-7 md:px-8">
      <div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-6"><div className="flex items-center gap-4"><div className="relative grid h-20 w-20 place-items-center rounded-full border-2 border-amber-400 bg-gradient-to-br from-amber-300 via-amber-600 to-amber-950 shadow-[0_0_35px_rgba(245,158,11,.35)]"><div className="grid h-[68px] w-[68px] place-items-center rounded-full bg-[#111522]"><Crown className="h-8 w-8 text-amber-300"/></div><i className="absolute -bottom-1 rounded-full border border-amber-400/50 bg-[#171106] px-2 py-0.5 text-[10px] font-black text-amber-200">LV {Math.max(1,mastered)}</i></div><div><p className="text-xs font-black uppercase tracking-[.3em] text-amber-400">Árbol de talentos</p><h2 className="mt-1 font-serif text-3xl font-black text-amber-50 drop-shadow-[0_2px_8px_rgba(245,158,11,.3)]">{discipline}</h2><p className="mt-1 text-sm font-bold text-slate-400">Rango: <span className="text-amber-200">{rank}</span></p></div></div><div className="min-w-64"><div className="mb-2 flex items-center justify-between text-xs font-black uppercase tracking-wider"><span className="text-slate-400">Maestría total</span><span className="text-amber-300">{mastered}/{allSkills.length} · {percent}%</span></div><div className="h-4 rounded-full border border-amber-500/30 bg-black/70 p-0.5 shadow-inner"><div className="relative h-full overflow-hidden rounded-full bg-gradient-to-r from-amber-800 via-amber-400 to-yellow-200 transition-all duration-500" style={{width:`${percent}%`}}><div className="absolute inset-0 animate-pulse bg-white/20"/></div></div><p className="mt-2 text-right text-[11px] text-slate-500">{training} talentos en entrenamiento</p></div></div>
    </header>

    <main className="relative px-4 py-9 md:px-8"><div className="mx-auto mb-12 flex max-w-md items-center justify-center"><div className="h-px flex-1 bg-gradient-to-r from-transparent to-amber-500/50"/><div className="mx-4 flex items-center gap-2 rounded-full border border-amber-500/30 bg-amber-500/10 px-4 py-2 text-xs font-black uppercase tracking-[.2em] text-amber-200"><Star className="h-4 w-4 fill-amber-300"/> Núcleo del guerrero</div><div className="h-px flex-1 bg-gradient-to-l from-transparent to-amber-500/50"/></div>
      <div className="mx-auto grid max-w-6xl gap-8 xl:grid-cols-2">{branches.map(([category,skills],branchIndex)=><TalentBranch key={category} category={category} skills={skills} branchIndex={branchIndex} progress={progress} editable={editable} saving={saving} onChange={onChange}/>)}</div>
      <div className="mx-auto mt-10 flex max-w-3xl flex-wrap justify-center gap-5 text-xs font-bold text-slate-400"><Legend style="locked" label="Bloqueado"/><Legend style="available" label="Disponible"/><Legend style="training" label="En entrenamiento"/><Legend style="mastered" label="Dominado"/></div>
    </main>
  </div>;
}

function TalentBranch({category,skills,branchIndex,progress,editable,saving,onChange}:{category:string;skills:readonly string[];branchIndex:number;progress:SkillProgress;editable:boolean;saving:boolean;onChange?:(next:SkillProgress)=>void}){
 const Icon=branchIcons[branchIndex%branchIcons.length];
 const branchMastered=skills.filter(skill=>progress[skill]==="dominada").length;
 return <section className="relative rounded-3xl border border-white/10 bg-gradient-to-b from-white/[.055] to-black/30 p-5 shadow-[inset_0_1px_rgba(255,255,255,.06)]"><div className="absolute -top-4 left-1/2 h-8 w-px -translate-x-1/2 bg-gradient-to-b from-amber-400/70 to-amber-400/10"/><header className="mb-8 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl border border-amber-400/40 bg-gradient-to-br from-amber-500/20 to-black text-amber-300 shadow-[0_0_20px_rgba(245,158,11,.12)]"><Icon className="h-6 w-6"/></span><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-amber-500">Senda {branchIndex+1}</p><h3 className="font-serif text-xl font-black text-amber-50">{category}</h3></div></div><span className="rounded-lg border border-white/10 bg-black/30 px-2.5 py-1 text-xs font-black text-slate-400">{branchMastered}/{skills.length}</span></header><div className="relative mx-auto flex max-w-sm flex-col items-center">{skills.map((skill,index)=>{
   const status=progress[skill]||"pendiente",prerequisite=index===0?null:skills[index-1],unlocked=index===0||progress[prerequisite!]==="dominada"||status!=="pendiente",canEdit=editable&&unlocked&&!saving;
   return <div key={skill} className="relative flex w-full flex-col items-center">{index>0&&<div className={cn("h-10 w-1",unlocked?"bg-gradient-to-b from-amber-300 via-amber-500 to-amber-700 shadow-[0_0_10px_rgba(245,158,11,.45)]":"bg-slate-800")}/>}<button type="button" disabled={!canEdit} onClick={()=>onChange?.({...progress,[skill]:nextSkillStatus(status)})} className="group relative flex w-full items-center gap-4 text-left disabled:cursor-default"><span className={cn("relative grid h-[76px] w-[76px] shrink-0 place-items-center [clip-path:polygon(25%_6.7%,75%_6.7%,100%_50%,75%_93.3%,25%_93.3%,0_50%)]",status==="dominada"?"bg-gradient-to-br from-yellow-200 via-amber-500 to-amber-900 shadow-[0_0_25px_rgba(245,158,11,.55)]":status==="practicando"?"bg-gradient-to-br from-cyan-200 via-blue-500 to-blue-950 shadow-[0_0_25px_rgba(59,130,246,.45)]":unlocked?"bg-gradient-to-br from-violet-300 via-violet-600 to-violet-950 shadow-[0_0_18px_rgba(139,92,246,.35)]":"bg-slate-800")}>{status==="dominada"&&<span className="absolute inset-[5px] grid place-items-center bg-[#161006] [clip-path:inherit]"><Check className="h-8 w-8 text-amber-300"/></span>}{status==="practicando"&&<span className="absolute inset-[5px] grid place-items-center bg-[#071525] [clip-path:inherit]"><Sparkles className="h-8 w-8 text-cyan-300"/></span>}{status==="pendiente"&&unlocked&&<span className="absolute inset-[5px] grid place-items-center bg-[#160c22] [clip-path:inherit]"><Star className="h-8 w-8 text-violet-300"/></span>}{!unlocked&&<span className="absolute inset-[5px] grid place-items-center bg-[#0c0e13] [clip-path:inherit]"><LockKeyhole className="h-7 w-7 text-slate-600"/></span>}</span><span className={cn("min-w-0 flex-1 rounded-xl border px-4 py-3 transition",status==="dominada"?"border-amber-400/35 bg-amber-500/10":status==="practicando"?"border-cyan-400/35 bg-cyan-500/10":unlocked?"border-violet-400/25 bg-violet-500/[.07]":"border-white/5 bg-black/20",canEdit&&"group-hover:-translate-y-0.5 group-hover:border-amber-300/50")}><b className={cn("block font-serif",unlocked?"text-white":"text-slate-600")}>{skill}</b><small className={cn("mt-0.5 block text-[11px] font-bold uppercase tracking-wide",status==="dominada"?"text-amber-300":status==="practicando"?"text-cyan-300":unlocked?"text-violet-300":"text-slate-700")}>{status==="dominada"?"Talento dominado":status==="practicando"?"Entrenamiento activo":unlocked?editable?"Pulsa para entrenar":"Talento disponible":`Requiere: ${prerequisite}`}</small></span></button></div>;
 })}</div></section>;
}

function Legend({style,label}:{style:"locked"|"available"|"training"|"mastered";label:string}){const classes={locked:"bg-slate-700",available:"bg-violet-400 shadow-[0_0_8px_rgb(167,139,250)]",training:"bg-cyan-400 shadow-[0_0_8px_rgb(34,211,238)]",mastered:"bg-amber-400 shadow-[0_0_8px_rgb(251,191,36)]"};return <span className="flex items-center gap-2"><i className={cn("h-2.5 w-2.5 rotate-45",classes[style])}/>{label}</span>}
