"use client";

import { useEffect,useMemo,useState } from "react";
import { collection,doc,onSnapshot,query,serverTimestamp,Timestamp,updateDoc,where } from "firebase/firestore";
import { CalendarCheck,CheckCircle2,Clock3,Loader2,MessageCircle,Phone,RefreshCw,Search,UserPlus,XCircle } from "lucide-react";
import { useFirestore,useUser } from "@/firebase";

type Status="pendiente"|"contactado"|"confirmada"|"cancelada";
type Request={id:string;nombre:string;telefono:string;disciplina:string;sede:string;horario:string;notas:string;estado:Status;creadoEn?:Timestamp};
const statusStyle:Record<Status,string>={pendiente:"bg-amber-500/15 text-amber-200 border-amber-400/20",contactado:"bg-violet-500/15 text-violet-200 border-violet-400/20",confirmada:"bg-emerald-500/15 text-emerald-200 border-emerald-400/20",cancelada:"bg-red-500/15 text-red-200 border-red-400/20"};

export default function TrialRequestsPage(){const db=useFirestore(),{user}=useUser(),[site,setSite]=useState("MMA"),[requests,setRequests]=useState<Request[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[filter,setFilter]=useState<Status|"todas">("pendiente"),[updating,setUpdating]=useState("");
 useEffect(()=>setSite(localStorage.getItem("userSede")||"MMA"),[]);
 useEffect(()=>{if(!db)return;setLoading(true);const siteRequests=query(collection(db,"SolicitudesClasePrueba"),where("sede","==",site));return onSnapshot(siteRequests,snapshot=>{setRequests(snapshot.docs.map(record=>({id:record.id,...record.data()} as Request)).sort((a,b)=>(b.creadoEn?.toMillis()||0)-(a.creadoEn?.toMillis()||0)));setLoading(false)},()=>setLoading(false))},[db,site]);
 const visible=useMemo(()=>{const term=search.trim().toLowerCase();return requests.filter(item=>(filter==="todas"||item.estado===filter)&&(!term||`${item.nombre} ${item.telefono} ${item.disciplina}`.toLowerCase().includes(term)))},[requests,filter,search]);
 const counts=useMemo(()=>({pendiente:requests.filter(item=>item.estado==="pendiente").length,contactado:requests.filter(item=>item.estado==="contactado").length,confirmada:requests.filter(item=>item.estado==="confirmada").length,cancelada:requests.filter(item=>item.estado==="cancelada").length}),[requests]);
 const setStatus=async(item:Request,status:Status)=>{if(!db||!user||updating)return;setUpdating(item.id);try{await updateDoc(doc(db,"SolicitudesClasePrueba",item.id),{estado:status,actualizadoEn:serverTimestamp(),actualizadoPor:user.uid})}finally{setUpdating("")}};
 return <main className="min-h-screen bg-slate-950 p-4 text-white md:p-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-bold text-violet-300"><UserPlus className="h-4 w-4"/> Prospectos del kiosco</p><h1 className="text-3xl font-black">Solicitudes de clase de prueba</h1><p className="mt-1 text-slate-400">Contacta, confirma y da seguimiento a cada solicitud.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3"><span className="text-xs uppercase text-slate-500">Sede</span><b className="ml-3">{site}</b></div></header>
 <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Pendientes" value={counts.pendiente} icon={Clock3} tone="text-amber-300"/><Summary label="Contactados" value={counts.contactado} icon={MessageCircle} tone="text-violet-300"/><Summary label="Confirmadas" value={counts.confirmada} icon={CheckCircle2} tone="text-emerald-300"/><Summary label="Canceladas" value={counts.cancelada} icon={XCircle} tone="text-red-300"/></section>
 <div className="mt-6 flex flex-wrap gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-3"><label className="relative min-w-60 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar nombre, teléfono o disciplina" className="h-11 w-full rounded-xl border border-white/10 bg-black/25 pl-10 pr-3 outline-none focus:border-violet-400"/></label><select value={filter} onChange={event=>setFilter(event.target.value as Status|"todas")} className="h-11 rounded-xl border border-white/10 bg-slate-950 px-4 font-bold"><option value="pendiente">Pendientes</option><option value="contactado">Contactados</option><option value="confirmada">Confirmadas</option><option value="cancelada">Canceladas</option><option value="todas">Todas</option></select></div>
 {loading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-violet-300"/></div>:visible.length===0?<div className="mt-6 rounded-3xl border border-dashed border-white/15 p-12 text-center"><CalendarCheck className="mx-auto h-9 w-9 text-slate-600"/><p className="mt-3 font-black">No hay solicitudes en este filtro</p></div>:<div className="mt-6 grid gap-4 xl:grid-cols-2">{visible.map(item=><article key={item.id} className="rounded-3xl border border-white/10 bg-white/[.04] p-5 shadow-xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black">{item.nombre}</h2><a href={`tel:${item.telefono}`} className="mt-1 flex items-center gap-2 text-sm text-slate-400 hover:text-white"><Phone className="h-3.5 w-3.5"/>{item.telefono}</a></div><span className={`rounded-full border px-3 py-1 text-[10px] font-black uppercase ${statusStyle[item.estado]}`}>{item.estado}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info label="Disciplina" value={item.disciplina}/><Info label="Horario" value={item.horario}/><Info label="Sede" value={item.sede}/><Info label="Recibida" value={item.creadoEn?.toDate().toLocaleString("es-MX",{dateStyle:"medium",timeStyle:"short"})||"Ahora"}/></div>{item.notas&&<p className="mt-4 rounded-xl bg-black/20 p-3 text-sm text-slate-300">{item.notas}</p>}<div className="mt-5 flex flex-wrap gap-2"><a href={`https://wa.me/52${item.telefono}`} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-xl bg-emerald-500 px-3 py-2 text-sm font-black text-slate-950"><MessageCircle className="h-4 w-4"/>WhatsApp</a>{item.estado!=="contactado"&&<Action disabled={updating===item.id} onClick={()=>setStatus(item,"contactado")} label="Contactado"/>}{item.estado!=="confirmada"&&<Action disabled={updating===item.id} onClick={()=>setStatus(item,"confirmada")} label="Confirmar"/>}{item.estado!=="cancelada"&&<Action disabled={updating===item.id} onClick={()=>setStatus(item,"cancelada")} label="Cancelar" danger/>}{item.estado!=="pendiente"&&<button type="button" disabled={updating===item.id} onClick={()=>setStatus(item,"pendiente")} className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 text-slate-400" aria-label="Regresar a pendiente"><RefreshCw className="h-4 w-4"/></button>}</div></article>)}</div>}</main>;
}
function Summary({label,value,icon:Icon,tone}:{label:string;value:number;icon:typeof Clock3;tone:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><Icon className={`h-5 w-5 ${tone}`}/><b className="mt-3 block text-3xl">{value}</b><span className="text-sm text-slate-500">{label}</span></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-black/20 p-3"><span className="block text-[10px] font-black uppercase text-slate-500">{label}</span><b className="mt-1 block text-slate-200">{value}</b></div>}
function Action({onClick,label,disabled,danger=false}:{onClick:()=>void;label:string;disabled:boolean;danger?:boolean}){return <button type="button" disabled={disabled} onClick={onClick} className={`rounded-xl border px-3 py-2 text-sm font-black disabled:opacity-40 ${danger?"border-red-400/20 bg-red-500/10 text-red-200":"border-white/10 bg-white/[.05] text-slate-200"}`}>{label}</button>}
