import { Crown, MapPin, Sparkles, Swords, Trophy } from "lucide-react";
import type { GameMatch } from "@/lib/game-room";
import { cn } from "@/lib/utils";

type Props = { schedule: GameMatch[]; currentRound?: number; viewerId?: string; title?: string };

export function TournamentBracket({ schedule, currentRound = 0, viewerId, title = "Cuadro del torneo" }: Props) {
  const rounds = Array.from(new Set(schedule.map((match) => match.round))).sort((a, b) => a - b);
  return <section className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#080c13]/90 p-5 shadow-[0_30px_100px_rgba(0,0,0,.45)] md:p-7">
    <div className="pointer-events-none absolute -left-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl"/><div className="pointer-events-none absolute -bottom-28 -right-20 h-80 w-80 rounded-full bg-violet-500/10 blur-3xl"/>
    <div className="relative flex items-center justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.25em] text-amber-300"><Trophy className="h-4 w-4"/> Competencia en vivo</p><h2 className="mt-2 text-2xl font-black md:text-3xl">{title}</h2></div><span className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-black text-white/55">{schedule.length} combates</span></div>
    <div className="relative mt-7 flex snap-x gap-5 overflow-x-auto pb-4">{rounds.map((round, roundIndex) => <div key={round} className="min-w-[290px] flex-1 snap-start animate-in fade-in slide-in-from-bottom-3" style={{ animationDelay: `${roundIndex * 90}ms`, animationFillMode: "both" }}><div className={cn("mb-3 flex items-center justify-between rounded-2xl border px-4 py-3", currentRound === round ? "border-emerald-300/30 bg-emerald-400/10" : "border-white/10 bg-white/[.035]")}><p className="text-xs font-black uppercase tracking-[.2em]">Round {round}</p>{currentRound === round && <span className="flex items-center gap-1 text-[10px] font-black uppercase text-emerald-300"><Sparkles className="h-3 w-3"/>En curso</span>}</div><div className="space-y-3">{schedule.filter((match) => match.round === round).map((match, index) => { const mine = viewerId === match.a.id || viewerId === match.b.id; return <article key={match.id} className={cn("relative overflow-hidden rounded-2xl border p-4 transition duration-300 hover:-translate-y-1", mine ? "border-cyan-300/50 bg-cyan-400/10 shadow-[0_0_28px_rgba(34,211,238,.12)]" : "border-white/10 bg-white/[.035]", match.estado === "completado" && "opacity-80")}><div className="absolute inset-y-0 left-0 w-1 bg-gradient-to-b from-cyan-300 to-violet-400"/><div className="flex items-center justify-between text-[10px] font-black uppercase tracking-wider text-white/40"><span className="flex items-center gap-1"><MapPin className="h-3 w-3"/>Área {match.area}</span><span>{match.estado === "en_curso" ? "● EN VIVO" : match.estado === "completado" ? "Finalizado" : `Match ${index + 1}`}</span></div><div className="mt-4 space-y-2"><div className={cn("flex items-center justify-between rounded-xl px-3 py-2", match.winnerId === match.a.id ? "bg-amber-300/15 text-amber-100" : "bg-black/25")}><span className="font-black">{match.a.nombre}</span>{match.winnerId === match.a.id && <Crown className="h-4 w-4 text-amber-300"/>}</div><div className="flex items-center gap-2 px-3 text-[9px] font-black uppercase tracking-[.2em] text-white/25"><span className="h-px flex-1 bg-white/10"/><Swords className="h-3 w-3"/><span className="h-px flex-1 bg-white/10"/></div><div className={cn("flex items-center justify-between rounded-xl px-3 py-2", match.winnerId === match.b.id ? "bg-amber-300/15 text-amber-100" : "bg-black/25")}><span className="font-black">{match.b.nombre}</span>{match.winnerId === match.b.id && <Crown className="h-4 w-4 text-amber-300"/>}</div></div>{match.solicitudMutua && <p className="mt-3 text-center text-[9px] font-black uppercase tracking-wider text-violet-300">Desafío mutuo</p>}</article>; })}</div></div>)}</div>
  </section>;
}
