"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import QRCode from "qrcode";
import { Ban, ClipboardCopy, QrCode, RefreshCw, ShieldCheck, TicketCheck, Users } from "lucide-react";

import { useAuth } from "@/firebase";
import { guestPassStatus, remainingUses, type GuestPass } from "@/lib/guest-pass";

type Share = { id: string; guestName: string; url: string; qr: string };
const statusLabels = { valid: "Válido", scheduled: "Programado", expired: "Vencido", used: "Agotado", revoked: "Revocado" } as const;

export default function GuestPassesAdminPage() {
  const auth = useAuth(); const [site, setSite] = useState("MMA"); const [passes, setPasses] = useState<GuestPass[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [share, setShare] = useState<Share | null>(null); const [filter, setFilter] = useState<"all" | "valid">("all"); const [form, setForm] = useState({ guestName: "", discipline: "Jiu-Jitsu", hostName: "", maxUses: 1, validHours: 24, notes: "" });
  useEffect(() => setSite(window.localStorage.getItem("userSede") || "MMA"), []);
  const bearer = useCallback(async () => ({ Authorization: `Bearer ${await auth.currentUser?.getIdToken()}` }), [auth]);
  const load = useCallback(async () => { if (!auth.currentUser) return; setLoading(true); try { const response = await fetch(`/api/admin/pases-invitados?sede=${encodeURIComponent(site)}`, { headers: await bearer(), cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setPasses(data.passes || []); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cargar."); } finally { setLoading(false); } }, [auth.currentUser, bearer, site]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => passes.filter((pass) => filter === "all" || guestPassStatus(pass) === "valid"), [filter, passes]); const stats = useMemo(() => ({ valid: passes.filter((pass) => guestPassStatus(pass) === "valid").length, visits: passes.reduce((sum, pass) => sum + pass.uses, 0), total: passes.length }), [passes]);
  async function action(body: Record<string, unknown>) { const response = await fetch("/api/admin/pases-invitados", { method: "POST", headers: { "Content-Type": "application/json", ...(await bearer()) }, body: JSON.stringify({ ...body, sede: site }) }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setPasses((current) => { const exists = current.some((pass) => pass.id === data.pass.id); return exists ? current.map((pass) => pass.id === data.pass.id ? data.pass : pass) : [data.pass, ...current]; }); return data; }
  async function showShare(data: { pass: GuestPass; url: string }) { const qr = await QRCode.toDataURL(data.url, { width: 440, margin: 1 }); setShare({ id: data.pass.id, guestName: data.pass.guestName, url: data.url, qr }); }
  async function create() { try { if (!form.guestName.trim()) throw new Error("Escribe el nombre del invitado."); const data = await action({ action: "create", ...form }); await showShare(data); setForm((current) => ({ ...current, guestName: "", notes: "" })); setMessage("Pase creado y listo para compartir."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo crear."); } }
  async function reissue(pass: GuestPass) { try { const data = await action({ action: "reissue", id: pass.id }); await showShare(data); setMessage("Se generó un QR nuevo; el anterior dejó de funcionar."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo generar."); } }
  async function revoke(pass: GuestPass) { if (!window.confirm(`¿Revocar el pase de ${pass.guestName}?`)) return; try { await action({ action: "revoke", id: pass.id }); if (share?.id === pass.id) setShare(null); setMessage("Pase revocado."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo revocar."); } }
  return <main className="min-h-screen bg-[#08090c] px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6"><header className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#1a1c22] to-[#0e1915] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-emerald-300"><TicketCheck className="h-4 w-4" /> Atletas · {site}</p><h1 className="mt-2 text-3xl font-black text-white sm:text-4xl">Pases QR para invitados</h1><p className="mt-2 text-sm text-white/60">Invitaciones temporales, usos limitados y registro de entradas.</p></div><button type="button" onClick={() => void load()} className="flex h-11 items-center gap-2 rounded-xl border border-white/20 px-4 font-black text-white"><RefreshCw className="h-4 w-4" /> Actualizar</button></div></header>
    <section className="grid gap-3 sm:grid-cols-3"><Stat icon={ShieldCheck} label="Pases vigentes" value={stats.valid} color="text-emerald-300" /><Stat icon={Users} label="Entradas registradas" value={stats.visits} color="text-sky-300" /><Stat icon={QrCode} label="Pases emitidos" value={stats.total} color="text-violet-300" /></section>
    <section className="grid gap-4 rounded-3xl border border-white/10 bg-[#17181d] p-5 md:grid-cols-2 lg:grid-cols-4"><Field label="Nombre del invitado"><input value={form.guestName} onChange={(event) => setForm({ ...form, guestName: event.target.value })} placeholder="Nombre completo" className="guest-input" /></Field><Field label="Disciplina"><select value={form.discipline} onChange={(event) => setForm({ ...form, discipline: event.target.value })} className="guest-input"><option>Jiu-Jitsu</option><option>Taekwondo</option><option>MMA</option><option>Clase de prueba</option><option>Evento</option></select></Field><Field label="Invitado por"><input value={form.hostName} onChange={(event) => setForm({ ...form, hostName: event.target.value })} placeholder="Atleta o profesor" className="guest-input" /></Field><Field label="Vigencia"><select value={form.validHours} onChange={(event) => setForm({ ...form, validHours: Number(event.target.value) })} className="guest-input"><option value={2}>2 horas</option><option value={8}>8 horas</option><option value={24}>24 horas</option><option value={72}>3 días</option><option value={168}>7 días</option></select></Field><Field label="Entradas permitidas"><input type="number" min="1" max="10" value={form.maxUses} onChange={(event) => setForm({ ...form, maxUses: Number(event.target.value) })} className="guest-input" /></Field><Field label="Notas"><input value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Opcional" className="guest-input" /></Field><button type="button" onClick={create} className="h-12 rounded-xl bg-emerald-400 font-black text-[#06110c] md:col-span-2"><TicketCheck className="mr-2 inline h-4 w-4" /> Crear pase y QR</button></section>
    {share && <section className="grid gap-5 rounded-3xl border border-emerald-400/25 bg-[#101a16] p-5 md:grid-cols-[260px_1fr] md:items-center"><Image src={share.qr} alt={`Pase de ${share.guestName}`} width={260} height={260} unoptimized className="mx-auto rounded-2xl bg-white p-3" /><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Pase listo</p><h2 className="mt-2 text-3xl font-black text-white">{share.guestName}</h2><p className="mt-2 text-white/60">Envía el enlace o muestra el QR. Al reemitirlo, este código se invalida.</p><button type="button" onClick={() => void navigator.clipboard.writeText(share.url)} className="mt-4 flex h-11 items-center gap-2 rounded-xl bg-white px-4 font-black text-[#08090c]"><ClipboardCopy className="h-4 w-4" /> Copiar enlace</button></div></section>}
    {message && <p className="rounded-xl border border-sky-300/20 bg-sky-300/10 px-4 py-3 text-sm font-bold text-sky-100">{message}</p>}
    <div className="flex gap-2"><button type="button" onClick={() => setFilter("all")} className={`rounded-xl px-4 py-2 font-black ${filter === "all" ? "bg-white text-[#08090c]" : "border border-white/15 text-white"}`}>Todos</button><button type="button" onClick={() => setFilter("valid")} className={`rounded-xl px-4 py-2 font-black ${filter === "valid" ? "bg-emerald-400 text-[#06110c]" : "border border-white/15 text-white"}`}>Vigentes</button></div>
    {loading ? <p className="rounded-2xl bg-[#17181d] p-8 text-center font-bold text-white/50">Cargando pases…</p> : visible.length === 0 ? <p className="rounded-2xl bg-[#17181d] p-8 text-center font-bold text-white/50">No hay pases en esta vista.</p> : <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((pass) => { const status = guestPassStatus(pass); return <article key={pass.id} className="rounded-2xl border border-white/10 bg-[#17181d] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-emerald-300">{pass.discipline}</p><h2 className="text-xl font-black text-white">{pass.guestName}</h2><p className="text-sm text-white/50">Invitado por: {pass.hostName || "Albatros"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${status === "valid" ? "bg-emerald-400/20 text-emerald-200" : "bg-white/10 text-white/50"}`}>{statusLabels[status]}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="Restantes" value={`${remainingUses(pass)}/${pass.maxUses}`} /><Metric label="Usadas" value={pass.uses} /></div><p className="mt-3 text-xs text-white/45">Vence: {pass.validUntil ? new Date(pass.validUntil).toLocaleString("es-MX") : "—"}</p>{pass.lastUsedAt && <p className="mt-1 text-xs text-white/45">Última entrada: {new Date(pass.lastUsedAt).toLocaleString("es-MX")}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={() => void reissue(pass)} className="h-11 rounded-xl border border-white/20 font-black text-white"><QrCode className="mr-1 inline h-4 w-4" /> Nuevo QR</button>{pass.active && <button type="button" onClick={() => void revoke(pass)} className="h-11 rounded-xl bg-red-500 font-black text-white"><Ban className="mr-1 inline h-4 w-4" /> Revocar</button>}</div></article>; })}</section>}
  </div><style jsx global>{`.guest-input{height:3rem;width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.15);background:#08090c;padding:0 .75rem;color:#fff;outline:none}.guest-input::placeholder{color:rgba(255,255,255,.3)}.guest-input:focus{border-color:#34d399}`}</style></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-bold text-white">{label}{children}</label>; }
function Stat({ icon: Icon, label, value, color }: { icon: typeof QrCode; label: string; value: number; color: string }) { return <article className="rounded-2xl border border-white/10 bg-[#17181d] p-4"><Icon className={`h-5 w-5 ${color}`} /><p className="mt-2 text-3xl font-black text-white">{value}</p><p className="text-xs font-black uppercase tracking-wide text-white/45">{label}</p></article>; }
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <p className="rounded-lg bg-black/20 p-3 text-xs font-bold text-white/45">{label}<strong className="block text-xl text-white">{value}</strong></p>; }
