"use client";

import { useCallback, useMemo, useState } from "react";
import { Clipboard, Dices, Globe2, Maximize2, Minimize2, RefreshCw, Swords } from "lucide-react";

import { GrapplingChessBoard } from "@/components/grappling-chess-board";
import { useAuth } from "@/firebase";
import { applyGrapplingChessMove, createGrapplingChessState, legalGrapplingChessMoves, rouletteGrapplingChessMove, type GrapplingChessMove, type GrapplingChessState } from "@/lib/grappling-chess";

type Mode = "free" | "roulette" | "online";
type OnlineRoom = { code: string; links: string[]; expiresAt: string };

export default function GrapplingChessAdminPage() {
  const auth = useAuth(); const [mode, setMode] = useState<Mode>("free"); const [names, setNames] = useState<[string,string]>(["Jugador rojo", "Jugador azul"]); const [state, setState] = useState<GrapplingChessState>(() => createGrapplingChessState()); const [rouletteMove, setRouletteMove] = useState<GrapplingChessMove | null>(null); const [fullscreen, setFullscreen] = useState(false); const [site] = useState(() => typeof window === "undefined" ? "MMA" : localStorage.getItem("userSede") || "MMA"); const [room, setRoom] = useState<OnlineRoom | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const moves = useMemo(() => legalGrapplingChessMoves(state), [state]);
  const bearer = useCallback(async () => ({ Authorization: `Bearer ${await auth.currentUser?.getIdToken()}` }), [auth]);
  function rename(player: 0 | 1, value: string) { const nextNames: [string,string] = player === 0 ? [value, names[1]] : [names[0], value]; setNames(nextNames); if (!state.history.length) setState(createGrapplingChessState(nextNames[0], nextNames[1])); }
  function restart(nextMode = mode) { const next = createGrapplingChessState(names[0], names[1]); setState(next); setRouletteMove(nextMode === "roulette" ? rouletteGrapplingChessMove(next) : null); setMessage(""); }
  function changeMode(next: Mode) { setMode(next); setFullscreen(false); if (next !== "online") restart(next); }
  function play(moveId: string) { try { const next = applyGrapplingChessMove(state, moveId); setState(next); setMessage(""); setRouletteMove(mode === "roulette" && next.winner === null ? rouletteGrapplingChessMove(next) : null); } catch (error) { setMessage(error instanceof Error ? error.message : "Movimiento inválido."); } }
  function spinAgain() { setRouletteMove(rouletteGrapplingChessMove(state)); }
  async function createOnline() { setBusy(true); setMessage(""); try { const response = await fetch("/api/admin/ajedrez", { method: "POST", headers: { "Content-Type": "application/json", ...(await bearer()) }, body: JSON.stringify({ sede: site, playerOne: names[0], playerTwo: names[1] }) }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setRoom(data); setMessage("Partida creada. Envía un enlace distinto a cada jugador."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo crear la partida."); } finally { setBusy(false); } }
  async function copy(value: string) { await navigator.clipboard.writeText(value); setMessage("Enlace copiado."); }
  const board = <GrapplingChessBoard state={state} moves={mode === "roulette" && rouletteMove ? moves : moves} requiredMove={mode === "roulette" ? rouletteMove : null} onMove={play} />;
  return <main className="min-h-screen bg-[#07090d] p-4 text-white sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px] space-y-5">
    <header className="overflow-hidden rounded-[2.25rem] border border-red-400/15 bg-[radial-gradient(circle_at_90%_0%,rgba(239,68,68,.24),transparent_34%),linear-gradient(135deg,#211015,#0b0d12_65%)] p-6 sm:p-8"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-red-300"><Swords className="h-4 w-4" /> Estrategia posicional · {site}</p><h1 className="mt-2 text-4xl font-black sm:text-6xl">Ajedrez de combate</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">Encadena derribos, pases, raspados, controles y escapes. La sumisión sólo aparece después de cerrar todas las salidas.</p></header>
    <nav className="grid gap-2 rounded-2xl border border-white/10 bg-[#12141a] p-2 sm:grid-cols-3">{([{id:"free",label:"Modo libre",detail:"Elige cualquier movimiento legal",icon:Swords},{id:"roulette",label:"Modo ruleta",detail:"La pantalla ordena la jugada",icon:Dices},{id:"online",label:"Modo en línea",detail:"Dos atletas desde sus teléfonos",icon:Globe2}] as const).map((item) => <button key={item.id} type="button" onClick={() => changeMode(item.id)} className={`flex min-h-16 items-center gap-3 rounded-xl px-4 text-left ${mode === item.id ? "bg-red-500 text-white" : "text-white/65 hover:bg-white/[.05]"}`}><item.icon className="h-5 w-5" /><span><b className="block">{item.label}</b><small className={mode === item.id ? "text-white/75" : "text-white/40"}>{item.detail}</small></span></button>)}</nav>
    <section className="grid gap-3 rounded-2xl border border-white/10 bg-[#12141a] p-4 md:grid-cols-[1fr_1fr_auto_auto]"><label className="grid gap-1 text-xs font-black uppercase tracking-wider text-red-300">Jugador rojo<input value={names[0]} onChange={(event) => rename(0, event.target.value)} disabled={state.history.length > 0} className="h-11 rounded-xl border border-white/10 bg-black/25 px-3 text-sm normal-case tracking-normal text-white disabled:opacity-50" /></label><label className="grid gap-1 text-xs font-black uppercase tracking-wider text-sky-300">Jugador azul<input value={names[1]} onChange={(event) => rename(1, event.target.value)} disabled={state.history.length > 0} className="h-11 rounded-xl border border-white/10 bg-black/25 px-3 text-sm normal-case tracking-normal text-white disabled:opacity-50" /></label>{mode !== "online" && <><button type="button" onClick={() => restart()} className="mt-5 inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-white/15 px-4 font-black"><RefreshCw className="h-4 w-4" /> Reiniciar</button><button type="button" onClick={() => setFullscreen(true)} className="mt-5 inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-white px-4 font-black text-black"><Maximize2 className="h-4 w-4" /> Pantalla</button></>}{mode === "roulette" && <button type="button" onClick={spinAgain} className="md:col-span-4 h-11 rounded-xl border border-amber-300/25 bg-amber-400/10 font-black text-amber-200"><Dices className="mr-2 inline h-4 w-4" /> Girar otra indicación</button>}</section>
    {message && <p className="rounded-xl border border-red-300/20 bg-red-400/10 px-4 py-3 text-sm font-bold text-red-100">{message}</p>}
    {mode !== "online" ? board : <section className="grid gap-5 lg:grid-cols-[1fr_1fr]"><article className="rounded-[2rem] border border-white/10 bg-[#12141a] p-6"><p className="text-xs font-black uppercase tracking-[.2em] text-red-300">Partida privada</p><h2 className="mt-2 text-3xl font-black">Dos enlaces, un solo tablero</h2><p className="mt-3 text-sm leading-6 text-white/55">El servidor guarda únicamente el estado actual y hasta 24 jugadas. Los teléfonos consultan cada 7 segundos y escriben sólo cuando alguien mueve.</p><button type="button" disabled={busy} onClick={() => void createOnline()} className="mt-6 h-12 w-full rounded-xl bg-red-500 font-black disabled:opacity-50">{busy ? "Creando…" : room ? "Crear otra partida" : "Crear partida en línea"}</button></article><article className="rounded-[2rem] border border-white/10 bg-[#12141a] p-6">{room ? <><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Sala {room.code}</p><h2 className="mt-2 text-2xl font-black">Invitaciones listas</h2><div className="mt-4 grid gap-3">{room.links.map((link, index) => <button key={link} type="button" onClick={() => void copy(link)} className="flex min-h-16 items-center justify-between rounded-2xl border border-white/10 bg-black/20 px-4 text-left"><span><small className={index === 0 ? "text-red-300" : "text-sky-300"}>JUGADOR {index + 1}</small><b className="block">{names[index]}</b></span><Clipboard className="h-5 w-5 text-white/45" /></button>)}</div><p className="mt-4 text-xs text-white/40">Vence en 8 horas. Cada enlace controla únicamente a su jugador.</p></> : <div className="grid min-h-64 place-items-center text-center text-white/35"><span><Globe2 className="mx-auto mb-3 h-10 w-10" />Aquí aparecerán los enlaces privados.</span></div>}</article></section>}
  </div>{fullscreen && <div className="fixed inset-0 z-[100] overflow-auto bg-[#07090d] p-4 text-white sm:p-7"><button type="button" onClick={() => setFullscreen(false)} className="fixed right-5 top-5 z-20 grid h-12 w-12 place-items-center rounded-2xl border border-white/15 bg-black/70"><Minimize2 /></button><div className="mx-auto max-w-[1500px] pt-12">{board}</div></div>}</main>;
}
