"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { Activity, ArrowLeft, AudioLines, Check, Dumbbell, HeartPulse, Maximize2, Minimize2, Pause, Play, RotateCcw, Timer, Volume2, VolumeX, Zap } from "lucide-react";

type Speed="control"|"cardio"|"turbo";
type Exercise={id:string;label:string;symbol:string;instruction:string;low:string};
const exercises:Exercise[]=[
 {id:"lagartijas",label:"LAGARTIJAS",symbol:"⬇",instruction:"Pecho al frente y cuerpo alineado",low:"Apoya las rodillas"},
 {id:"jab-cross",label:"JAB · CROSS",symbol:"1–2",instruction:"Guardia arriba y regreso rápido",low:"Trabaja sin potencia"},
 {id:"abdominal",label:"ABDOMINAL",symbol:"ABS",instruction:"Sube con control",low:"Reduce el recorrido"},
 {id:"crunch",label:"CRUNCH",symbol:"⌃",instruction:"Contracción corta y controlada",low:"Manos sobre los muslos"},
 {id:"burpee",label:"BURPEE",symbol:"↕",instruction:"Suelo, plancha, regreso y salto",low:"Sin salto; camina a plancha"},
 {id:"rodillas",label:"RODILLAS ALTAS",symbol:"KNEE",instruction:"Alterna rodillas con brazos activos",low:"Marcha rápida"},
 {id:"sentadilla",label:"SENTADILLAS",symbol:"▾",instruction:"Cadera atrás y pecho arriba",low:"Menor profundidad"},
 {id:"jumping-jack",label:"JUMPING JACK",symbol:"✦",instruction:"Abre piernas y brazos a la vez",low:"Abre un pie por vez"},
];
const speeds:Record<Speed,{label:string;interval:number;detail:string}>={control:{label:"Control",interval:5000,detail:"5 segundos"},cardio:{label:"Cardio",interval:3000,detail:"3 segundos"},turbo:{label:"Turbo",interval:1500,detail:"1.5 segundos"}};

export default function TabataPuzzlePage(){
 const [speed,setSpeed]=useState<Speed>("cardio"),[duration,setDuration]=useState(60),[selected,setSelected]=useState<Record<string,boolean>>(()=>Object.fromEntries(exercises.map(item=>[item.id,true]))),[sound,setSound]=useState(true),[voice,setVoice]=useState(false),[lowImpact,setLowImpact]=useState(false),[presentation,setPresentation]=useState(false),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[countdown,setCountdown]=useState(0),[remaining,setRemaining]=useState(60),[current,setCurrent]=useState<Exercise|null>(null),[next,setNext]=useState<Exercise|null>(null),[changes,setChanges]=useState(0),[progress,setProgress]=useState(0);const clockRef=useRef<ReturnType<typeof setInterval>|null>(null),exerciseRef=useRef<ReturnType<typeof setInterval>|null>(null),introRef=useRef<ReturnType<typeof setInterval>|null>(null),lastRef=useRef(""),currentRef=useRef<Exercise|null>(null),nextRef=useRef<Exercise|null>(null),wakeRef=useRef<{release:()=>Promise<void>}|null>(null);
 const enabled=useMemo(()=>exercises.filter(item=>selected[item.id]),[selected]);
 const clearTimers=useCallback(()=>{if(clockRef.current)clearInterval(clockRef.current);if(exerciseRef.current)clearInterval(exerciseRef.current);if(introRef.current)clearInterval(introRef.current);clockRef.current=null;exerciseRef.current=null;introRef.current=null},[]);
 const beep=useCallback((frequency=850)=>{if(!sound)return;try{const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext,ctx=new AudioContextClass(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=frequency;gain.gain.setValueAtTime(.1,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.09);osc.connect(gain);gain.connect(ctx.destination);osc.onended=()=>void ctx.close();osc.start();osc.stop(ctx.currentTime+.1)}catch{/* El ejercicio continúa aunque el audio sea bloqueado. */}},[sound]);
 const speak=useCallback((text:string)=>{if(!voice||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const message=new SpeechSynthesisUtterance(text);message.lang="es-MX";message.rate=speed==="turbo"?1.8:1.35;message.volume=.85;window.speechSynthesis.speak(message)},[speed,voice]);
 const choose=useCallback((exclude="")=>{let pool=enabled.filter(item=>item.id!==exclude&&item.id!==lastRef.current);if(!pool.length)pool=enabled.filter(item=>item.id!==exclude);if(!pool.length)pool=enabled;const item=pool[Math.floor(Math.random()*pool.length)];lastRef.current=item.id;return item},[enabled]);
 const showNext=useCallback(()=>{const exercise=nextRef.current||choose(currentRef.current?.id||"");currentRef.current=exercise;setCurrent(exercise);const upcoming=choose(exercise.id);nextRef.current=upcoming;setNext(upcoming);setChanges(value=>value+1);beep();speak(exercise.label)},[beep,choose,speak]);
 const finish=useCallback(()=>{clearTimers();setRunning(false);setPaused(false);setCurrent(null);setNext(null);setProgress(100);beep(1050);speak("Cardio completado");void wakeRef.current?.release().catch(()=>undefined);wakeRef.current=null},[beep,clearTimers,speak]);
 const beginTimers=useCallback(()=>{showNext();exerciseRef.current=setInterval(showNext,speeds[speed].interval);clockRef.current=setInterval(()=>setRemaining(value=>{const result=value-1;setProgress(((duration-result)/duration)*100);if(result<=0){queueMicrotask(finish);return 0}return result}),1000)},[duration,finish,showNext,speed]);
 async function start(){if(!enabled.length)return;clearTimers();currentRef.current=null;nextRef.current=choose();setRemaining(duration);setProgress(0);setChanges(0);setCurrent(null);setNext(nextRef.current);setPaused(false);setRunning(true);setCountdown(3);if("wakeLock" in navigator){try{wakeRef.current=await navigator.wakeLock.request("screen")}catch{/* Wake Lock es opcional. */}}let value=3;introRef.current=setInterval(()=>{value-=1;setCountdown(value);beep(600+(3-value)*100);if(value<=0){if(introRef.current)clearInterval(introRef.current);introRef.current=null;beginTimers()}},1000)}
 function togglePause(){if(!running)return;if(paused){setPaused(false);beginTimers()}else{if(clockRef.current)clearInterval(clockRef.current);if(exerciseRef.current)clearInterval(exerciseRef.current);clockRef.current=null;exerciseRef.current=null;setPaused(true);window.speechSynthesis?.cancel()}}
 function reset(){clearTimers();setRunning(false);setPaused(false);setCountdown(0);setRemaining(duration);setProgress(0);setChanges(0);setCurrent(null);setNext(null);currentRef.current=null;nextRef.current=null;window.speechSynthesis?.cancel();void wakeRef.current?.release().catch(()=>undefined);wakeRef.current=null}
 async function openScreen(){setPresentation(true);try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch{/* La capa visual continúa disponible. */}}
 async function closeScreen(){setPresentation(false);try{if(document.fullscreenElement)await document.exitFullscreen()}catch{/* La capa se cierra igualmente. */}}
 useEffect(()=>{if(!running)setRemaining(duration)},[duration,running]);useEffect(()=>()=>{clearTimers();window.speechSynthesis?.cancel();void wakeRef.current?.release().catch(()=>undefined)},[clearTimers]);
 const clock=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,"0")}`;
 return <main className="min-h-screen bg-[#08090c] p-4 text-white sm:p-6 lg:p-8"><div className="mx-auto max-w-[1600px] space-y-6"><header className="overflow-hidden rounded-[2.25rem] border border-white/10 bg-[radial-gradient(circle_at_85%_0%,rgba(249,115,22,.22),transparent_36%),linear-gradient(135deg,#211108,#0c0d11_65%)] p-6 shadow-2xl sm:p-8"><Link href="/admin/puzzle" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-orange-300"><ArrowLeft className="h-4 w-4"/>Puzzle Hub</Link><div className="mt-5 flex flex-col justify-between gap-6 xl:flex-row xl:items-end"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-orange-300"><HeartPulse className="h-4 w-4"/> Puzzle 02 · Cardio continuo</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-6xl">Tabata</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300 sm:text-base">Los ejercicios cambian de forma continua, sin descansos entre uno y otro. Cada pitido indica un cambio inmediato.</p></div><button onClick={()=>void openScreen()} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-orange-400 px-6 font-black text-orange-950"><Maximize2/>Pantalla para alumnos</button></div></header>
 <section className="grid gap-5 xl:grid-cols-[430px_1fr]"><aside className="space-y-5 rounded-[2rem] border border-white/10 bg-[#121319] p-5"><Config title="Velocidad de cambio" icon={Zap}><div className="grid grid-cols-3 gap-2">{(Object.keys(speeds) as Speed[]).map(key=><button key={key} disabled={running} onClick={()=>setSpeed(key)} className={`min-h-24 rounded-2xl border p-2 text-xs font-black disabled:opacity-40 ${speed===key?'border-orange-300/35 bg-orange-500/15 text-orange-200':'border-white/10 bg-black/20 text-slate-400'}`}><span className="block">{speeds[key].label}</span><b className="mt-2 block text-base">{speeds[key].detail}</b></button>)}</div></Config><Config title="Duración total" icon={Timer}><div className="grid grid-cols-3 gap-2">{[60,120,180].map(value=><button key={value} disabled={running} onClick={()=>setDuration(value)} className={`h-14 rounded-xl border font-black disabled:opacity-40 ${duration===value?'border-orange-300/35 bg-orange-500/15 text-orange-200':'border-white/10 bg-black/20 text-slate-400'}`}>{value/60} min</button>)}</div></Config><Config title={`Ejercicios activos (${enabled.length})`} icon={Dumbbell}><div className="grid grid-cols-2 gap-2">{exercises.map(exercise=><button key={exercise.id} disabled={running} onClick={()=>setSelected(value=>({...value,[exercise.id]:!value[exercise.id]}))} className={`flex min-h-12 items-center justify-between rounded-xl border px-3 text-left text-xs font-black disabled:opacity-40 ${selected[exercise.id]?'border-emerald-300/20 bg-emerald-500/10 text-white':'border-white/10 bg-black/20 text-slate-600'}`}>{exercise.label}{selected[exercise.id]&&<Check className="h-4 w-4 text-emerald-300"/>}</button>)}</div></Config><div className="grid grid-cols-3 gap-2"><Option active={sound} onClick={()=>setSound(value=>!value)} icon={sound?AudioLines:VolumeX} label="Pitidos"/><Option active={voice} onClick={()=>setVoice(value=>!value)} icon={voice?Volume2:VolumeX} label="Voz"/><Option active={lowImpact} onClick={()=>setLowImpact(value=>!value)} icon={Activity} label="Bajo impacto"/></div><button onClick={()=>void start()} disabled={running||!enabled.length} className="flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-orange-400 font-black text-orange-950 disabled:opacity-40"><Play/>Iniciar cardio</button></aside>
  <div className="space-y-4"><WorkoutBoard exercise={current} next={next} clock={clock} countdown={countdown} running={running} paused={paused} lowImpact={lowImpact}/><div className="grid grid-cols-3 gap-3"><Stat label="Tiempo" value={clock}/><Stat label="Cambios" value={String(changes)}/><Stat label="Progreso" value={`${Math.round(progress)}%`}/></div><div className="flex justify-center gap-2"><button onClick={reset} className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/10 bg-white/[.05] px-4 font-bold"><RotateCcw className="h-4 w-4"/>Reiniciar</button><button onClick={togglePause} disabled={!running||countdown>0} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-amber-300 px-6 font-black text-amber-950 disabled:opacity-40">{paused?<Play/>:<Pause/>}{paused?"Continuar":"Pausar"}</button></div></div></section>
 </div>{presentation&&<TabataScreen exercise={current} next={next} clock={clock} countdown={countdown} running={running} paused={paused} lowImpact={lowImpact} progress={progress} changes={changes} onStart={()=>void start()} onPause={togglePause} onReset={reset} onClose={()=>void closeScreen()}/>}</main>
}

function WorkoutBoard({exercise,next,clock,countdown,running,paused,lowImpact}:{exercise:Exercise|null;next:Exercise|null;clock:string;countdown:number;running:boolean;paused:boolean;lowImpact:boolean}){return <section className="grid min-h-[570px] place-items-center overflow-hidden rounded-[2rem] border border-orange-300/20 bg-[radial-gradient(circle_at_center,rgba(249,115,22,.16),transparent_62%),#101116] p-5 text-center">{paused?<PauseView/>:countdown>0?<Countdown value={countdown}/>:exercise?<ExerciseView exercise={exercise} next={next} clock={clock} lowImpact={lowImpact}/>:<div><HeartPulse className="mx-auto h-24 w-24 text-orange-300"/><h2 className="mt-5 text-4xl font-black sm:text-6xl">CARDIO CONTINUO</h2><p className="mt-3 text-slate-500">Sin descansos entre ejercicios</p></div>}<span className="sr-only">{running?"Sesión en curso":"Sesión lista"}</span></section>}
function ExerciseView({exercise,next,clock,lowImpact,large=false}:{exercise:Exercise;next:Exercise|null;clock:string;lowImpact:boolean;large?:boolean}){return <div><div className={`mx-auto grid place-items-center rounded-[2.5rem] bg-gradient-to-br from-orange-300 to-red-500 font-black text-orange-950 shadow-[0_0_80px_rgba(249,115,22,.17)] ${large?'h-52 w-52 text-7xl sm:h-72 sm:w-72 sm:text-9xl':'h-40 w-40 text-6xl sm:h-48 sm:w-48'}`}>{exercise.symbol}</div><p className="mt-6 text-sm font-black uppercase tracking-[.25em] text-orange-300">AHORA</p><h2 className={`mt-2 font-black leading-none ${large?'text-6xl sm:text-9xl':'text-4xl sm:text-6xl'}`}>{exercise.label}</h2><p className={`mx-auto mt-5 max-w-2xl font-bold text-slate-300 ${large?'text-xl sm:text-2xl':'text-sm sm:text-base'}`}>{lowImpact?exercise.low:exercise.instruction}</p><div className="mt-7 flex flex-wrap items-center justify-center gap-3"><span className="rounded-full border border-white/10 bg-black/25 px-4 py-2 font-mono text-xl font-black tabular-nums">{clock}</span>{next&&<span className="rounded-full border border-white/10 bg-white/[.05] px-4 py-2 text-xs font-black text-white/50">SIGUE: {next.label}</span>}</div></div>}
function TabataScreen({exercise,next,clock,countdown,running,paused,lowImpact,progress,changes,onStart,onPause,onReset,onClose}:{exercise:Exercise|null;next:Exercise|null;clock:string;countdown:number;running:boolean;paused:boolean;lowImpact:boolean;progress:number;changes:number;onStart:()=>void;onPause:()=>void;onReset:()=>void;onClose:()=>void}){return <div className="fixed inset-0 z-[100] overflow-hidden bg-[#100806] text-white"><div className="absolute inset-x-0 top-0 h-2 bg-white/10"><div className="h-full bg-orange-400 transition-[width] duration-1000" style={{width:`${progress}%`}}/></div><header className="absolute inset-x-0 top-2 z-20 flex items-center justify-between p-4 sm:p-6"><div><p className="text-xs font-black uppercase tracking-[.24em] text-orange-300">Puzzle · Tabata continuo</p><p className="mt-1 text-sm text-white/50">Sin descansos · {changes} cambios</p></div><b className="rounded-2xl border border-white/10 bg-white/[.06] px-5 py-2 font-mono text-3xl tabular-nums sm:text-5xl">{clock}</b><button onClick={onClose} className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/[.06]" aria-label="Cerrar"><Minimize2/></button></header><main className="grid h-full place-items-center px-4 pb-28 pt-24 text-center">{paused?<PauseView/>:countdown>0?<Countdown value={countdown}/>:exercise?<ExerciseView exercise={exercise} next={next} clock={clock} lowImpact={lowImpact} large/>:<div><HeartPulse className="mx-auto h-32 w-32 text-orange-300"/><h2 className="mt-6 text-7xl font-black sm:text-9xl">TABATA</h2></div>}</main><footer className="absolute inset-x-0 bottom-0 flex items-center justify-center gap-2 border-t border-white/10 bg-black/55 p-4 backdrop-blur-xl"><button onClick={onReset} className="grid h-12 w-12 place-items-center rounded-xl border border-white/10 bg-white/[.06]"><RotateCcw/></button>{running?<button onClick={onPause} disabled={countdown>0} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-amber-300 px-7 font-black text-amber-950 disabled:opacity-40">{paused?<Play/>:<Pause/>}{paused?"Continuar":"Pausar"}</button>:<button onClick={onStart} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-orange-400 px-7 font-black text-orange-950"><Play/>Iniciar</button>}</footer></div>}
function Countdown({value}:{value:number}){return <div><p className="text-xl font-black uppercase tracking-[.3em] text-white/50">Prepárense</p><b className="mt-4 block animate-pulse text-[10rem] font-black leading-none text-orange-300 sm:text-[16rem]">{value}</b></div>}
function PauseView(){return <div><Pause className="mx-auto h-28 w-28 text-amber-300"/><h2 className="mt-5 text-6xl font-black sm:text-8xl">PAUSA</h2></div>}
function Config({title,icon:Icon,children}:{title:string;icon:typeof Timer;children:React.ReactNode}){return <fieldset><legend className="mb-2 flex items-center gap-2 text-sm font-black"><Icon className="h-4 w-4 text-orange-300"/>{title}</legend>{children}</fieldset>}
function Option({active,onClick,icon:Icon,label}:{active:boolean;onClick:()=>void;icon:typeof AudioLines;label:string}){return <button onClick={onClick} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl border text-[10px] font-black uppercase ${active?'border-emerald-300/25 bg-emerald-500/10 text-emerald-100':'border-white/10 bg-black/20 text-slate-600'}`}><Icon className="h-4 w-4"/>{label}</button>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-[#121319] p-4 text-center"><span className="text-[9px] font-black uppercase tracking-wider text-slate-500">{label}</span><b className="mt-1 block font-mono text-xl tabular-nums">{value}</b></div>}
