"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { CalendarDays,ChevronRight,CreditCard,DoorOpen,Fullscreen,LogIn,ShieldCheck,UserPlus,X } from "lucide-react";
import { Logo } from "@/components/logo";

const actions=[
  {href:"/login",label:"Acceso atletas",description:"Ingresa a tu cuenta y consulta tu progreso.",icon:LogIn,tone:"from-red-500/25 to-red-950/20",iconTone:"bg-red-500 text-white"},
  {href:"/pagar",label:"Realizar un pago",description:"Consulta y completa una solicitud de pago.",icon:CreditCard,tone:"from-emerald-500/20 to-emerald-950/20",iconTone:"bg-emerald-400 text-slate-950"},
  {href:"/#horarios",label:"Consultar horarios",description:"Revisa disciplinas, días y horarios disponibles.",icon:CalendarDays,tone:"from-amber-500/20 to-amber-950/20",iconTone:"bg-amber-400 text-slate-950"},
  {href:"/#servicios",label:"Clase de prueba",description:"Conoce las disciplinas y agenda tu primera clase.",icon:UserPlus,tone:"from-violet-500/20 to-violet-950/20",iconTone:"bg-violet-400 text-slate-950"},
] as const;

export default function KioskPage(){const router=useRouter(),[now,setNow]=useState(new Date()),[exitOpen,setExitOpen]=useState(false),[pin,setPin]=useState(""),[error,setError]=useState("");
 useEffect(()=>{localStorage.setItem("albatrosKioskMode","1");const timer=window.setInterval(()=>setNow(new Date()),1000);return()=>window.clearInterval(timer)},[]);
 const enterFullscreen=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch{/* El navegador puede negar pantalla completa; el kiosco sigue operativo. */}};
 const exit=async(event:React.FormEvent)=>{event.preventDefault();if(pin!=="1908"){setError("PIN incorrecto");setPin("");return}localStorage.removeItem("albatrosKioskMode");if(document.fullscreenElement)await document.exitFullscreen();router.push("/")};
 return <main className="relative min-h-screen overflow-hidden bg-[#050609] p-4 text-white sm:p-7 lg:p-10"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_15%_10%,rgba(239,68,68,.18),transparent_28%),radial-gradient(circle_at_85%_80%,rgba(139,92,246,.14),transparent_30%)]"/><header className="relative mx-auto flex max-w-6xl items-center justify-between gap-4"><Logo heading={false}/><div className="flex items-center gap-2"><button type="button" onClick={enterFullscreen} className="flex min-h-12 items-center gap-2 rounded-2xl border border-white/10 bg-white/[.06] px-4 font-bold text-slate-200 backdrop-blur-xl hover:bg-white/10"><Fullscreen className="h-4 w-4"/><span className="hidden sm:inline">Pantalla completa</span></button><button type="button" onClick={()=>setExitOpen(true)} className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/[.06] text-slate-300 backdrop-blur-xl" aria-label="Salir del modo kiosco"><X className="h-5 w-5"/></button></div></header>
 <section className="relative mx-auto mt-10 max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-black uppercase tracking-[.22em] text-red-400">Autoservicio Albatros</p><h1 className="mt-2 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">¿Qué deseas hacer?</h1><p className="mt-3 text-lg text-slate-400">Selecciona una opción para comenzar.</p></div><div className="text-right"><p className="text-4xl font-black tabular-nums">{now.toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"})}</p><p className="text-sm capitalize text-slate-500">{now.toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long"})}</p></div></div>
 <div className="mt-9 grid gap-4 md:grid-cols-2">{actions.map(({href,label,description,icon:Icon,tone,iconTone})=><Link key={href} href={href} className={`group relative min-h-44 overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br ${tone} p-6 shadow-[0_24px_70px_rgba(0,0,0,.35),inset_0_1px_rgba(255,255,255,.12)] backdrop-blur-2xl transition hover:-translate-y-1 hover:border-white/20`}><div className="flex h-full items-start gap-5"><span className={`grid h-16 w-16 shrink-0 place-items-center rounded-2xl ${iconTone} shadow-lg`}><Icon className="h-7 w-7"/></span><div className="min-w-0"><h2 className="text-2xl font-black">{label}</h2><p className="mt-2 max-w-sm text-slate-400">{description}</p></div><ChevronRight className="ml-auto mt-5 h-6 w-6 text-white/40 transition group-hover:translate-x-1 group-hover:text-white"/></div></Link>)}</div></section>
 <footer className="relative mx-auto mt-8 flex max-w-6xl items-center justify-center gap-2 text-sm text-slate-600"><ShieldCheck className="h-4 w-4"/>Tus datos se protegen y la sesión se cierra al terminar.</footer>
 {exitOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-md"><form onSubmit={exit} className="w-full max-w-sm rounded-[2rem] border border-white/15 bg-[#111217]/95 p-6 shadow-2xl"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-red-500/15 text-red-400"><DoorOpen className="h-5 w-5"/></span><div><h2 className="font-black">Salir del modo kiosco</h2><p className="text-sm text-slate-500">Introduce el PIN administrativo.</p></div></div><input autoFocus type="password" inputMode="numeric" maxLength={4} value={pin} onChange={event=>{setPin(event.target.value.replace(/\D/g,"").slice(0,4));setError("")}} className="mt-5 h-14 w-full rounded-2xl border border-white/10 bg-black/30 text-center text-2xl font-black tracking-[.5em] outline-none focus:border-red-400" placeholder="••••" aria-label="PIN para salir"/>{error&&<p className="mt-2 text-sm font-bold text-red-400">{error}</p>}<div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={()=>{setExitOpen(false);setPin("");setError("")}} className="rounded-xl border border-white/10 px-4 py-3 font-bold text-slate-300">Cancelar</button><button type="submit" disabled={pin.length!==4} className="rounded-xl bg-red-500 px-4 py-3 font-black disabled:opacity-40">Salir</button></div></form></div>}</main>;
}
