"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Image from "next/image";
import QRCode from "qrcode";
import { BarChart3, ClipboardCopy, MessageSquareHeart, Plus, QrCode, RefreshCw, StopCircle, Users } from "lucide-react";

import { useAuth } from "@/firebase";
import { SURVEY_QUESTIONS, surveyOverall, type ClassSurvey } from "@/lib/class-survey";

type Share = { id: string; url: string; qr: string; className: string };

export default function ClassSurveysAdminPage() {
  const auth = useAuth(); const [site, setSite] = useState("MMA"); const [surveys, setSurveys] = useState<ClassSurvey[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [share, setShare] = useState<Share | null>(null); const [form, setForm] = useState({ className: "", discipline: "Jiu-Jitsu", instructorName: "", hours: 8 });
  useEffect(() => setSite(window.localStorage.getItem("userSede") || "MMA"), []);
  const bearer = useCallback(async () => ({ Authorization: `Bearer ${await auth.currentUser?.getIdToken()}` }), [auth]);
  const load = useCallback(async () => { if (!auth.currentUser) return; setLoading(true); try { const response = await fetch(`/api/admin/encuestas-clase?sede=${encodeURIComponent(site)}`, { headers: await bearer(), cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setSurveys(data.surveys || []); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cargar."); } finally { setLoading(false); } }, [auth.currentUser, bearer, site]);
  useEffect(() => { void load(); }, [load]);
  const totals = useMemo(() => ({ active: surveys.filter((item) => item.active).length, responses: surveys.reduce((sum, item) => sum + item.responseCount, 0) }), [surveys]);

  async function action(body: Record<string, unknown>) { const response = await fetch("/api/admin/encuestas-clase", { method: "POST", headers: { "Content-Type": "application/json", ...(await bearer()) }, body: JSON.stringify({ ...body, sede: site }) }); const data = await response.json(); if (!response.ok) throw new Error(data.mensaje); setSurveys((current) => { const exists = current.some((item) => item.id === data.survey.id); return exists ? current.map((item) => item.id === data.survey.id ? data.survey : item) : [data.survey, ...current]; }); return data; }
  async function showShare(data: { survey: ClassSurvey; url: string }) { const qr = await QRCode.toDataURL(data.url, { width: 440, margin: 1 }); setShare({ id: data.survey.id, url: data.url, qr, className: data.survey.className }); }
  async function create() { try { if (!form.className.trim()) throw new Error("Escribe el nombre de la clase."); const data = await action({ action: "create", ...form }); await showShare(data); setForm((current) => ({ ...current, className: "" })); setMessage("Encuesta creada y lista para escanear."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo crear."); } }
  async function renew(survey: ClassSurvey) { try { const data = await action({ action: "renew", id: survey.id, hours: form.hours }); await showShare(data); setMessage("Se generó un nuevo QR. El anterior dejó de funcionar."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo generar."); } }
  async function close(survey: ClassSurvey) { try { await action({ action: "close", id: survey.id }); if (share?.id === survey.id) setShare(null); setMessage("Encuesta cerrada."); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo cerrar."); } }

  return <main className="min-h-screen bg-[#08090c] px-4 py-6 text-white sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6">
    <header className="rounded-3xl border border-white/10 bg-gradient-to-br from-[#1a1c22] to-[#12141a] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-violet-300"><MessageSquareHeart className="h-4 w-4" /> Comunicación · {site}</p><h1 className="mt-2 text-3xl font-black text-white sm:text-4xl">Encuestas rápidas de clase</h1><p className="mt-2 text-sm text-white/60">Opiniones anónimas mediante QR, resultados inmediatos y un solo voto por dispositivo.</p></div><button type="button" onClick={() => void load()} className="flex h-11 items-center gap-2 rounded-xl border border-white/20 px-4 font-black text-white"><RefreshCw className="h-4 w-4" /> Actualizar</button></div></header>
    <section className="grid gap-3 sm:grid-cols-3"><Stat icon={QrCode} label="Encuestas activas" value={totals.active} color="text-emerald-300" /><Stat icon={Users} label="Respuestas" value={totals.responses} color="text-sky-300" /><Stat icon={BarChart3} label="Encuestas creadas" value={surveys.length} color="text-violet-300" /></section>
    <section className="grid gap-4 rounded-3xl border border-white/10 bg-[#17181d] p-5 md:grid-cols-2 lg:grid-cols-4"><Field label="Nombre de la clase"><input value={form.className} onChange={(event) => setForm({ ...form, className: event.target.value })} placeholder="Ej. No-Gi intermedios" className="input" /></Field><Field label="Disciplina"><select value={form.discipline} onChange={(event) => setForm({ ...form, discipline: event.target.value })} className="input"><option>Jiu-Jitsu</option><option>Taekwondo</option><option>MMA</option><option>Funcional</option><option>Otra</option></select></Field><Field label="Profesor"><input value={form.instructorName} onChange={(event) => setForm({ ...form, instructorName: event.target.value })} placeholder="Opcional" className="input" /></Field><Field label="Vigencia"><select value={form.hours} onChange={(event) => setForm({ ...form, hours: Number(event.target.value) })} className="input"><option value={2}>2 horas</option><option value={8}>8 horas</option><option value={24}>24 horas</option><option value={48}>48 horas</option></select></Field><button type="button" onClick={create} className="h-12 rounded-xl bg-violet-400 font-black text-[#100719] md:col-span-2 lg:col-span-4"><Plus className="mr-2 inline h-4 w-4" /> Crear encuesta y QR</button></section>
    {share && <section className="grid gap-5 rounded-3xl border border-emerald-400/25 bg-[#101a16] p-5 md:grid-cols-[260px_1fr] md:items-center"><Image src={share.qr} alt={`QR de ${share.className}`} width={260} height={260} unoptimized className="mx-auto rounded-2xl bg-white p-3" /><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Lista para responder</p><h2 className="mt-2 text-3xl font-black text-white">{share.className}</h2><p className="mt-2 text-white/60">Muestra este QR al terminar la clase. Si generas otro, este enlace se invalida.</p><button type="button" onClick={() => void navigator.clipboard.writeText(share.url)} className="mt-4 flex h-11 items-center gap-2 rounded-xl bg-white px-4 font-black text-[#08090c]"><ClipboardCopy className="h-4 w-4" /> Copiar enlace</button></div></section>}
    {message && <p className="rounded-xl border border-sky-300/20 bg-sky-300/10 px-4 py-3 text-sm font-bold text-sky-100">{message}</p>}
    {loading ? <p className="rounded-2xl bg-[#17181d] p-8 text-center font-bold text-white/50">Cargando encuestas…</p> : surveys.length === 0 ? <p className="rounded-2xl bg-[#17181d] p-8 text-center font-bold text-white/50">Todavía no hay encuestas.</p> : <section className="grid gap-4 lg:grid-cols-2">{surveys.map((survey) => <article key={survey.id} className="rounded-2xl border border-white/10 bg-[#17181d] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-violet-300">{survey.discipline}</p><h2 className="text-xl font-black text-white">{survey.className}</h2><p className="text-sm text-white/50">{survey.instructorName || "Profesor no especificado"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${survey.active ? "bg-emerald-400/20 text-emerald-200" : "bg-white/10 text-white/50"}`}>{survey.active ? "Activa" : "Cerrada"}</span></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Respuestas" value={survey.responseCount} /><Metric label="Promedio" value={surveyOverall(survey) ? `${surveyOverall(survey)}/5` : "—"} /><Metric label="Recomienda" value={survey.responseCount ? `${survey.averages.recommendation}/10` : "—"} /></div><div className="mt-3 grid grid-cols-2 gap-2">{SURVEY_QUESTIONS.map(({ key, label }) => <p key={key} className="rounded-lg bg-black/20 p-2 text-xs text-white/50">{label}<strong className="block text-lg text-white">{survey.responseCount ? survey.averages[key] : "—"}</strong></p>)}</div>{survey.comments.length > 0 && <details className="mt-3 rounded-lg bg-black/20 p-3"><summary className="cursor-pointer text-sm font-black text-white">Comentarios ({survey.comments.length})</summary><div className="mt-2 grid gap-2">{survey.comments.map((comment, index) => <p key={`${comment.at}-${index}`} className="border-t border-white/10 pt-2 text-sm text-white/65">{comment.text}</p>)}</div></details>}<div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={() => void renew(survey)} className="h-11 rounded-xl border border-white/20 font-black text-white"><QrCode className="mr-1 inline h-4 w-4" /> Nuevo QR</button>{survey.active ? <button type="button" onClick={() => void close(survey)} className="h-11 rounded-xl bg-red-500 font-black text-white"><StopCircle className="mr-1 inline h-4 w-4" /> Cerrar</button> : <button type="button" onClick={() => void renew(survey)} className="h-11 rounded-xl bg-emerald-400 font-black text-[#06110c]">Reabrir</button>}</div></article>)}</section>}
  </div><style jsx global>{`.input{height:3rem;width:100%;border-radius:.75rem;border:1px solid rgba(255,255,255,.15);background:#08090c;padding:0 .75rem;color:#fff;outline:none}.input::placeholder{color:rgba(255,255,255,.3)}.input:focus{border-color:#c084fc}`}</style></main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-bold text-white">{label}{children}</label>; }
function Stat({ icon: Icon, label, value, color }: { icon: typeof QrCode; label: string; value: number; color: string }) { return <article className="rounded-2xl border border-white/10 bg-[#17181d] p-4"><Icon className={`h-5 w-5 ${color}`} /><p className="mt-2 text-3xl font-black text-white">{value}</p><p className="text-xs font-black uppercase tracking-wide text-white/45">{label}</p></article>; }
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <p className="rounded-lg bg-white/[.05] p-3 text-xs font-bold text-white/45">{label}<strong className="block text-xl text-white">{value}</strong></p>; }
