"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BellRing, Check, Maximize2, Minimize2, Pause, Play, RotateCcw, Settings2, Volume2, VolumeX } from "lucide-react";

type Side="rojo"|"azul";
const sideStyle={rojo:{label:"ROJO",surface:"from-red-500 to-red-700",soft:"bg-red-500/15 border-red-300/25 text-red-200",text:"text-red-300"},azul:{label:"AZUL",surface:"from-blue-500 to-blue-700",soft:"bg-blue-500/15 border-blue-300/25 text-blue-200",text:"text-blue-300"}};

export default function BeepPuzzlePage(){
 const [beepsPerSide,setBeepsPerSide]=useState(10),[startSide,setStartSide]=useState<Side>("rojo"),[sound,setSound]=useState(true),[presentation,setPresentation]=useState(false),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[countdown,setCountdown]=useState(0),[activeSide,setActiveSide]=useState<Side>("rojo"),[redCount,setRedCount]=useState(0),[blueCount,setBlueCount]=useState(0),[total,setTotal]=useState(0),[flash,setFlash]=useState(0),[complete,setComplete]=useState(false);const intervalRef=useRef<ReturnType<typeof setInterval>|null>(null),introRef=useRef<ReturnType<typeof setInterval>|null>(null),sideRef=useRef<Side>("rojo"),redRef=useRef(0),blueRef=useRef(0),wakeRef=useRef<{release:()=>Promise<void>}|null>(null);
 const clearTimers=useCallback(()=>{if(intervalRef.current)clearInterval(intervalRef.current);if(introRef.current)clearInterval(introRef.current);intervalRef.current=null;introRef.current=null},[]);
 const beep=useCallback((side:Side)=>{if(!sound)return;try{const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext,ctx=new AudioContextClass(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=side==="rojo"?720:940;gain.gain.setValueAtTime(.13,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.11);osc.connect(gain);gain.connect(ctx.destination);osc.onended=()=>void ctx.close();osc.start();osc.stop(ctx.currentTime+.12)}catch{/* La secuencia visual continúa aunque el audio sea bloqueado. */}},[sound]);
 const finish=useCallback(()=>{clearTimers();setRunning(false);setPaused(false);setComplete(true);void wakeRef.current?.release().catch(()=>undefined);wakeRef.current=null},[clearTimers]);
 const strike=useCallback(()=>{const side=sideRef.current;if(side==="rojo"){redRef.current+=1;setRedCount(redRef.current)}else{blueRef.current+=1;setBlueCount(blueRef.current)}setActiveSide(side);setTotal(value=>value+1);setFlash(value=>value+1);beep(side);const finished=redRef.current>=beepsPerSide&&blueRef.current>=beepsPerSide;if(finished){queueMicrotask(finish);return}sideRef.current=side==="rojo"?"azul":"rojo"},[beep,beepsPerSide,finish]);
 const begin=useCallback(()=>{strike();intervalRef.current=setInterval(strike,1000)},[strike]);
 async function start(){clearTimers();redRef.current=0;blueRef.current=0;sideRef.current=startSide;setActiveSide(startSide);setRedCount(0);setBlueCount(0);setTotal(0);setFlash(0);setComplete(false);setPaused(false);setRunning(true);setCountdown(3);if("wakeLock" in navigator){try{wakeRef.current=await navigator.wakeLock.request("screen")}catch{/* Wake Lock es opcional. */}}let value=3;introRef.current=setInterval(()=>{value-=1;setCountdown(value);if(value<=0){if(introRef.current)clearInterval(introRef.current);introRef.current=null;begin()}},1000)}
 function togglePause(){if(!running)return;if(paused){setPaused(false);intervalRef.current=setInterval(strike,1000)}else{if(intervalRef.current)clearInterval(intervalRef.current);intervalRef.current=null;setPaused(true)}}
 function reset(){clearTimers();setRunning(false);setPaused(false);setCountdown(0);setActiveSide(startSide);setRedCount(0);setBlueCount(0);setTotal(0);setFlash(0);setComplete(false);redRef.current=0;blueRef.current=0;sideRef.current=startSide;void wakeRef.current?.release().catch(()=>undefined);wakeRef.current=null}
 async function openScreen(){setPresentation(true);try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch{/* La presentación visual continúa disponible. */}}
 async function closeScreen(){setPresentation(false);try{if(document.fullscreenElement)await document.exitFullscreen()}catch{/* La capa se cierra igualmente. */}}
 useEffect(()=>()=>{clearTimers();void wakeRef.current?.release().catch(()=>undefined)},[clearTimers]);
 const progress=Math.min(100,(total/(beepsPerSide*2))*100),remaining=beepsPerSide*2-total;
 return <main className="min-h-screen bg-[#07090d] p-4 text-white sm:p-6 lg:p-8"><div className="mx-auto max-w-[1500px] space-y-6"><header className="overflow-hidden rounded-[2.25rem] border border-white/10 bg-[radial-gradient(circle_at_15%_0%,rgba(239,68,68,.2),transparent_34%),radial-gradient(circle_at_85%_0%,rgba(59,130,246,.2),transparent_34%),linear-gradient(135deg,#17090c,#080d18)] p-6 shadow-2xl sm:p-8"><Link href="/admin/puzzle" className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-white/60"><ArrowLeft className="h-4 w-4"/>Puzzle Hub</Link><div className="mt-5 flex flex-col justify-between gap-6 xl:flex-row xl:items-end"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-red-300"><BellRing className="h-4 w-4"/> Puzzle 04 · Reacción alternada</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-6xl">Pitidos rojo y azul</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300 sm:text-base">Cada pitido equivale a un golpe. Los turnos se alternan cada segundo: rojo, azul, rojo, azul.</p></div><button onClick={()=>void openScreen()} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-white px-6 font-black text-slate-950"><Maximize2/>Pantalla para alumnos</button></div></header>
 <section className="grid gap-5 xl:grid-cols-[390px_1fr]"><aside className="h-fit space-y-5 rounded-[2rem] border border-white/10 bg-[#11141a] p-5"><Config title="Golpes por cada lado"><div className="grid grid-cols-4 gap-2">{[5,10,15,20].map(value=><button key={value} disabled={running} onClick={()=>setBeepsPerSide(value)} className={`h-14 rounded-xl border font-black disabled:opacity-40 ${beepsPerSide===value?'border-white/30 bg-white text-slate-950':'border-white/10 bg-black/20 text-slate-400'}`}>{value}</button>)}</div><label className="mt-3 block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-wider text-slate-500">Cantidad personalizada</span><input type="number" min="1" max="100" disabled={running} value={beepsPerSide} onChange={event=>setBeepsPerSide(Math.min(100,Math.max(1,Number(event.target.value)||1)))} className="h-12 w-full rounded-xl border border-white/10 bg-black/30 px-3 font-mono font-black text-white outline-none focus:border-white/30 disabled:opacity-40"/></label></Config><Config title="Primer turno"><div className="grid grid-cols-2 gap-2">{(["rojo","azul"] as Side[]).map(side=><button key={side} disabled={running} onClick={()=>{setStartSide(side);setActiveSide(side)}} className={`min-h-14 rounded-xl border font-black uppercase disabled:opacity-40 ${startSide===side?sideStyle[side].soft:'border-white/10 bg-black/20 text-slate-500'}`}>{side}</button>)}</div></Config><button onClick={()=>setSound(value=>!value)} className={`flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border font-black ${sound?'border-emerald-300/25 bg-emerald-500/10 text-emerald-100':'border-white/10 bg-black/20 text-slate-500'}`}>{sound?<Volume2/>:<VolumeX/>}{sound?"Pitidos activados":"Pitidos silenciados"}</button><div className="grid grid-cols-2 gap-2"><button onClick={()=>void start()} disabled={running} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl bg-white font-black text-slate-950 disabled:opacity-40"><Play/>Iniciar</button><button onClick={reset} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.05] font-bold"><RotateCcw/>Reiniciar</button></div></aside>
  <div className="space-y-4"><SignalBoard side={activeSide} countdown={countdown} running={running} paused={paused} complete={complete} flash={flash}/><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Rojo" value={`${redCount}/${beepsPerSide}`} tone="text-red-300"/><Stat label="Azul" value={`${blueCount}/${beepsPerSide}`} tone="text-blue-300"/><Stat label="Restantes" value={String(Math.max(0,remaining))}/><Stat label="Intervalo" value="1.0 s"/></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-gradient-to-r from-red-500 via-white to-blue-500 transition-[width] duration-300" style={{width:`${progress}%`}}/></div><div className="flex justify-center"><button onClick={togglePause} disabled={!running||countdown>0} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-amber-300 px-7 font-black text-amber-950 disabled:opacity-40">{paused?<Play/>:<Pause/>}{paused?"Continuar":"Pausar"}</button></div></div></section>
 </div>{presentation&&<SignalScreen side={activeSide} countdown={countdown} running={running} paused={paused} complete={complete} red={redCount} blue={blueCount} target={beepsPerSide} progress={progress} flash={flash} onStart={()=>void start()} onPause={togglePause} onReset={reset} onClose={()=>void closeScreen()}/>}</main>
}

function SignalBoard({side,countdown,running,paused,complete,flash}:{side:Side;countdown:number;running:boolean;paused:boolean;complete:boolean;flash:number}){return <section className="grid min-h-[560px] place-items-center overflow-hidden rounded-[2rem] border border-white/10 bg-[#0b0d12] p-5 text-center">{countdown>0?<Countdown value={countdown}/>:paused?<PauseView/>:complete?<Complete/>:running?<Signal side={side} flash={flash}/>:<div><BellRing className="mx-auto h-24 w-24 text-white/15"/><h2 className="mt-5 text-4xl font-black sm:text-6xl">LISTOS PARA GOLPEAR</h2><p className="mt-3 text-slate-500">Un pitido cada 1.0 segundo</p></div>}</section>}
function Signal({side,flash,large=false}:{side:Side;flash:number;large?:boolean}){const style=sideStyle[side];return <div key={`${side}-${flash}`} className="animate-[pulse_.32s_ease-out_1] text-center"><div className={`mx-auto grid place-items-center rounded-full bg-gradient-to-br ${style.surface} font-black text-white shadow-[0_0_100px_rgba(255,255,255,.14)] ${large?'h-64 w-64 text-9xl sm:h-96 sm:w-96 sm:text-[12rem]':'h-52 w-52 text-8xl sm:h-72 sm:w-72 sm:text-9xl'}`}>●</div><p className={`mt-7 font-black tracking-tight ${large?'text-7xl sm:text-[10rem]':'text-6xl sm:text-8xl'}`}>{style.label}</p><span className={`mt-4 inline-flex rounded-full border px-5 py-2 text-sm font-black uppercase tracking-[.25em] ${style.soft}`}>¡GOLPEA!</span></div>}
function SignalScreen({side,countdown,running,paused,complete,red,blue,target,progress,flash,onStart,onPause,onReset,onClose}:{side:Side;countdown:number;running:boolean;paused:boolean;complete:boolean;red:number;blue:number;target:number;progress:number;flash:number;onStart:()=>void;onPause:()=>void;onReset:()=>void;onClose:()=>void}){return <div className={`fixed inset-0 z-[100] overflow-hidden text-white transition-colors duration-200 ${side==="rojo"?'bg-[#170305]':'bg-[#030a1b]'}`}><div className="absolute inset-x-0 top-0 h-2 bg-white/10"><div className="h-full bg-white transition-[width] duration-300" style={{width:`${progress}%`}}/></div><header className="absolute inset-x-0 top-2 z-20 flex items-center justify-between p-4 sm:p-6"><div><p className={`text-xs font-black uppercase tracking-[.24em] ${sideStyle[side].text}`}>Puzzle · Pitidos</p><p className="text-sm text-white/50">Alternancia cada 1.0 segundo</p></div><div className="flex gap-3"><div className="rounded-2xl border border-red-300/20 bg-red-500/10 px-4 py-2 text-center"><b className="text-2xl text-red-200">{red}/{target}</b></div><div className="rounded-2xl border border-blue-300/20 bg-blue-500/10 px-4 py-2 text-center"><b className="text-2xl text-blue-200">{blue}/{target}</b></div><button onClick={onClose} className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/[.07]" aria-label="Cerrar"><Minimize2/></button></div></header><main className="grid h-full place-items-center px-4 pb-28 pt-24">{countdown>0?<Countdown value={countdown}/>:paused?<PauseView/>:complete?<Complete/>:running?<Signal side={side} flash={flash} large/>:<div className="text-center"><BellRing className="mx-auto h-32 w-32 text-white/20"/><h2 className="mt-6 text-6xl font-black sm:text-9xl">PREPÁRENSE</h2></div>}</main><footer className="absolute inset-x-0 bottom-0 flex items-center justify-center gap-2 border-t border-white/10 bg-black/50 p-4 backdrop-blur-xl"><button onClick={onReset} className="grid h-12 w-12 place-items-center rounded-xl border border-white/10 bg-white/[.07]"><RotateCcw/></button>{running?<button onClick={onPause} disabled={countdown>0} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-amber-300 px-7 font-black text-amber-950 disabled:opacity-40">{paused?<Play/>:<Pause/>}{paused?"Continuar":"Pausar"}</button>:<button onClick={onStart} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-7 font-black text-slate-950"><Play/>Iniciar</button>}</footer></div>}
function Countdown({value}:{value:number}){return <div className="text-center"><p className="text-xl font-black uppercase tracking-[.3em] text-white/50">Prepárense</p><b className="mt-4 block animate-pulse text-[10rem] font-black leading-none sm:text-[16rem]">{value}</b></div>}
function PauseView(){return <div className="text-center"><Pause className="mx-auto h-28 w-28 text-amber-300"/><h2 className="mt-5 text-6xl font-black sm:text-8xl">PAUSA</h2></div>}
function Complete(){return <div className="text-center"><Check className="mx-auto h-28 w-28 rounded-full bg-emerald-400 p-6 text-emerald-950"/><h2 className="mt-6 text-5xl font-black sm:text-8xl">COMPLETADO</h2></div>}
function Config({title,children}:{title:string;children:React.ReactNode}){return <fieldset><legend className="mb-2 flex items-center gap-2 text-sm font-black"><Settings2 className="h-4 w-4 text-white/60"/>{title}</legend>{children}</fieldset>}
function Stat({label,value,tone="text-white"}:{label:string;value:string;tone?:string}){return <div className="rounded-2xl border border-white/10 bg-[#11141a] p-4 text-center"><span className="text-[9px] font-black uppercase tracking-wider text-slate-500">{label}</span><b className={`mt-1 block font-mono text-2xl tabular-nums ${tone}`}>{value}</b></div>}
