"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { collection,doc,getDocs,query,updateDoc,where } from "firebase/firestore";
import { Activity,Calculator,Dumbbell,History,Ruler,Save } from "lucide-react";
import { useFirestore,useUser } from "@/firebase";
import { AdminAthletePicker,type ProgressAthlete } from "@/components/progress/admin-athlete-picker";
import { PhysicalHistory } from "@/components/progress/physical-history";
import { PhysicalTestLab } from "@/components/progress/physical-test-lab";
import { calculateBmi,calculateWaistHeight,calculateWaistHip,estimateAdultBodyFat,optionalNumber,wellnessScore,type PhysicalAssessment } from "@/lib/athlete-progress";

type Section="composition"|"tests"|"history";
const compositionFields=[['pesoKg','Peso','kg',true],['estaturaCm','Estatura','cm',true],['grasaPorcentaje','Grasa corporal','%',false],['cuelloCm','Cuello','cm',false],['hombrosCm','Hombros','cm',false],['pechoCm','Pecho','cm',false],['brazoCm','Brazo','cm',false],['antebrazoCm','Antebrazo','cm',false],['cinturaCm','Cintura','cm',false],['abdomenCm','Abdomen','cm',false],['caderaCm','Cadera','cm',false],['musloCm','Muslo','cm',false],['pantorrillaCm','Pantorrilla','cm',false]] as const;
const testFields=[['lagartijas','Lagartijas','repeticiones'],['sentadillas','Sentadillas','repeticiones'],['abdominales','Abdominales','repeticiones'],['navetteNivel','Course Navette','nivel'],['navetteIdas','Course Navette','idas completadas']] as const;

export default function AdminPhysicalPage(){
 const db=useFirestore(),{user}=useUser(); const [site,setSite]=useState('MMA'),[athletes,setAthletes]=useState<ProgressAthlete[]>([]),[selectedId,setSelectedId]=useState(''),[section,setSection]=useState<Section>('composition'),[autoFat,setAutoFat]=useState(false),[form,setForm]=useState<Record<string,string>>({fecha:new Date().toISOString().slice(0,10),sexoCalculo:'masculino'}),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>setSite(localStorage.getItem('userSede')||'MMA'),[]);
 const load=useCallback(async()=>{if(!db)return;const snap=await getDocs(query(collection(db,'Alumnos'),where('sede','==',site)));const list=snap.docs.filter(d=>d.data().activo!==false).map(d=>({id:d.id,nombre:String(d.data().nombre||'Atleta'),disciplina:String(d.data().disciplina||''),historialFisico:Array.isArray(d.data().historialFisico)?d.data().historialFisico:[]})).sort((a,b)=>a.nombre.localeCompare(b.nombre,'es'));setAthletes(list);setSelectedId(value=>list.some(a=>a.id===value)?value:list[0]?.id||'')},[db,site]);useEffect(()=>{void load()},[load]);
 const selected=athletes.find(a=>a.id===selectedId),records=useMemo(()=>(selected?.historialFisico||[]) as PhysicalAssessment[],[selected]);
 const weight=optionalNumber(form.pesoKg||''),height=optionalNumber(form.estaturaCm||''),waist=optionalNumber(form.cinturaCm||''),hip=optionalNumber(form.caderaCm||'');
 const bmi=calculateBmi(weight||0,height||0),waistHeight=calculateWaistHeight(waist,height),waistHip=calculateWaistHip(waist,hip),age=optionalNumber(form.edad||''),sex=form.sexoCalculo as "masculino"|"femenino",estimatedFat=estimateAdultBodyFat(bmi,age,sex),activeFat=autoFat?estimatedFat:optionalNumber(form.grasaPorcentaje||''),score=wellnessScore({bmi,waistHeight,bodyFat:activeFat,sex});
 const set=(key:string,value:string)=>{setForm(current=>({...current,[key]:value}));setMessage('')};
 async function save(){if(!db||!selected||!bmi||!form.fecha||(autoFat&&!estimatedFat))return;setSaving(true);setMessage('');const record:Record<string,string|number|boolean>={id:crypto.randomUUID(),fecha:form.fecha,imc:bmi,registradoPor:user?.email||'personal',grasaAutomatica:autoFat};for(const [key] of [...compositionFields,...testFields]){const number=optionalNumber(form[key]||'');if(number!==undefined&&key!=="grasaPorcentaje")record[key]=number}if(waistHeight!==undefined)record.cinturaEstatura=waistHeight;if(waistHip!==undefined)record.cinturaCadera=waistHip;if(age!==undefined)record.edad=age;record.sexoCalculo=sex;if(activeFat!==undefined)record.grasaPorcentaje=activeFat;if(autoFat)record.metodoGrasa='Estimación Deurenberg (IMC, edad y sexo)';else if(form.metodoGrasa)record.metodoGrasa=form.metodoGrasa.trim();if(form.notas)record.notas=form.notas.trim();const history=[record as unknown as PhysicalAssessment,...records].slice(0,30);try{await updateDoc(doc(db,'Alumnos',selected.id),{historialFisico:history});setAthletes(current=>current.map(a=>a.id===selected.id?{...a,historialFisico:history}:a));setMessage('Evaluación guardada correctamente.');setSection('history')}catch(error){setMessage(error instanceof Error?error.message:'No se pudo guardar la evaluación.')}finally{setSaving(false)}}
 return <main className="min-h-screen bg-slate-950 p-4 text-white md:p-8"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-bold text-cyan-300"><Activity className="h-4 w-4"/> Expediente de rendimiento</p><h1 className="text-3xl font-black">Estado físico</h1><p className="mt-1 max-w-2xl text-slate-400">Registra composición corporal y pruebas por separado. Los indicadores y cambios se calculan automáticamente.</p></div><button onClick={save} disabled={!selected||!bmi||saving} className="flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-black text-slate-950 disabled:opacity-40"><Save className="h-4 w-4"/>{saving?'Guardando…':'Guardar evaluación'}</button></header>
 <section className="mb-6 rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="grid gap-4 md:grid-cols-[1fr_220px]"><AdminAthletePicker athletes={athletes} selectedId={selectedId} onSelect={setSelectedId}/><Field label="Fecha de evaluación" unit="" required><input type="date" value={form.fecha||''} onChange={e=>set('fecha',e.target.value)} className="w-full rounded-xl border border-white/15 bg-slate-950 p-3 text-white"/></Field></div></section>
 <nav className="mb-6 grid gap-2 rounded-2xl border border-white/10 bg-black/20 p-2 sm:grid-cols-3" aria-label="Secciones de estado físico"><Tab active={section==='composition'} onClick={()=>setSection('composition')} icon={Ruler} label="Medidas y porcentajes"/><Tab active={section==='tests'} onClick={()=>setSection('tests')} icon={Dumbbell} label="Pruebas físicas"/><Tab active={section==='history'} onClick={()=>setSection('history')} icon={History} label={`Historial (${records.length})`}/></nav>
 {section==='composition'&&<div className="grid gap-6 xl:grid-cols-[1fr_360px]"><section className="rounded-3xl border border-white/10 bg-slate-900/70 p-5"><SectionTitle icon={Ruler} title="Composición y medidas" subtitle="Captura medidas directas o estima el PGC automáticamente."/><label className="mb-5 flex cursor-pointer items-center justify-between gap-4 rounded-2xl border border-cyan-400/20 bg-cyan-500/[.08] p-4"><span><b className="block text-white">Calcular PGC automáticamente</b><small className="text-slate-400">Usa IMC, edad y sexo con la fórmula Deurenberg para adultos.</small></span><input type="checkbox" checked={autoFat} onChange={e=>setAutoFat(e.target.checked)} className="h-6 w-11 accent-cyan-400"/></label>{autoFat&&<div className="mb-5 grid gap-4 sm:grid-cols-2"><NumberField label="Edad" unit="años" required value={form.edad||''} onChange={value=>set('edad',value)}/><Field label="Sexo usado por la fórmula" unit="" required><select value={sex} onChange={e=>set('sexoCalculo',e.target.value)} className="w-full rounded-xl border border-white/15 bg-slate-950 p-3 text-white"><option value="masculino">Masculino</option><option value="femenino">Femenino</option></select></Field></div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{compositionFields.filter(([key])=>!(autoFat&&key==='grasaPorcentaje')).map(([key,label,unit,required])=><NumberField key={key} label={label} unit={unit} required={required} value={form[key]||''} onChange={value=>set(key,value)}/>)}</div><div className="mt-4 grid gap-4 md:grid-cols-2">{!autoFat&&<Field label="Método para medir grasa" unit=""><input value={form.metodoGrasa||''} onChange={e=>set('metodoGrasa',e.target.value)} placeholder="Bioimpedancia, plicómetro…" className="w-full rounded-xl border border-white/15 bg-slate-950 p-3 text-white placeholder:text-slate-600"/></Field>}<Field label="Notas" unit=""><input value={form.notas||''} onChange={e=>set('notas',e.target.value)} placeholder="Condiciones de la medición…" className="w-full rounded-xl border border-white/15 bg-slate-950 p-3 text-white placeholder:text-slate-600"/></Field></div></section><aside className="rounded-3xl border border-cyan-400/20 bg-cyan-500/[.07] p-5"><SectionTitle icon={Calculator} title="Análisis automático" subtitle="Indicadores actualizados en tiempo real."/><div className="space-y-3"><Calculated label="Puntuación orientativa" value={score} suffix="/100"/><Calculated label="PGC estimado" value={autoFat?estimatedFat:activeFat} suffix="%"/><Calculated label="Índice de masa corporal" value={bmi||undefined}/><Calculated label="Cintura / estatura" value={waistHeight}/><Calculated label="Cintura / cadera" value={waistHip}/></div><p className="mt-5 text-xs leading-relaxed text-slate-400">El PGC automático es una estimación para adultos y puede diferir de una medición clínica. La puntuación resume únicamente los indicadores disponibles.</p></aside></div>}
 {section==='tests'&&<PhysicalTestLab values={form} onChange={set}/>} 
 {section==='history'&&<PhysicalHistory records={records}/>} {message&&<p role="status" className={`mt-5 rounded-xl p-3 text-sm ${message.includes('correctamente')?'bg-emerald-500/15 text-emerald-200':'bg-red-500/15 text-red-200'}`}>{message}</p>}</main>;
}
function Tab({active,onClick,icon:Icon,label}:{active:boolean;onClick:()=>void;icon:typeof Ruler;label:string}){return <button type="button" onClick={onClick} className={`flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-black transition ${active?'bg-cyan-400 text-slate-950':'text-slate-400 hover:bg-white/[.05] hover:text-white'}`}><Icon className="h-4 w-4"/>{label}</button>}
function SectionTitle({icon:Icon,title,subtitle}:{icon:typeof Ruler;title:string;subtitle:string}){return <div className="mb-5 flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-cyan-500/15 text-cyan-300"><Icon className="h-5 w-5"/></span><div><h2 className="font-black text-white">{title}</h2><p className="text-sm text-slate-400">{subtitle}</p></div></div>}
function Field({label,unit,required=false,children}:{label:string;unit:string;required?:boolean;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-400">{label}{unit&&` (${unit})`}{required&&' *'}</span>{children}</label>}
function NumberField({label,unit,required=false,value,onChange}:{label:string;unit:string;required?:boolean;value:string;onChange:(value:string)=>void}){return <Field label={label} unit={unit} required={required}><input type="number" min="0" step="0.1" inputMode="decimal" value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-white/15 bg-slate-950 p-3 text-white outline-none focus:border-cyan-400"/></Field>}
function Calculated({label,value,suffix=""}:{label:string;value?:number;suffix?:string}){return <div className="rounded-2xl border border-white/10 bg-slate-950/70 p-4"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</span><b className="mt-1 block text-2xl text-white">{value===undefined?'—':`${value}${suffix}`}</b></div>}
